export const dossierNodes = {
    "LUSTRA_CHEM-USE_LOG_77B-A": { id: "LUSTRA_CHEM-USE_LOG_77B-A", label: "INCIDENT REPORT: NIGHT FURY AMBUSH", folder: "Cryo-Chamber Grid" },
    "BASE_ICEHALLOW_003C": { id: "BASE_ICEHALLOW_003C", label: "BASE ICEHALLOW - 003C", folder: "Cryo-Chamber Grid" },
    "DIREWOLF_RESCUE-DOC_78A": { id: "DIREWOLF_RESCUE-DOC_78A", label: "DIREWOLF EXTRACTION REPORT", folder:"Dossier Compilation" },
    "TAPE_ERZA_XX17": { id: "TAPE_ERZA_XX17", label: "TAPE_ERZA_XX17", folder: "Dossier Compilation" },
    "OMPF_GHOSTPAW_001A": { id: "OMPF_GHOSTPAW_001A", label: "OMPF_GHOSTPAW_001A", folder: "Dossier Compilation" },
    "OMPF_ERZA_002B": { id: "OMPF_ERZA_002B", label: "OMPF_ERZA_002B", folder: "Dossier Compilation" },
    "COMP_DIREWOLF_114X": { id: "COMP_DIREWOLF_114X", label: "COMP_DIREWOLF_114X", folder: "Dossier Compilation" },
    "VOICE_S13-ENTRY_01A": { id: "VOICE_S13-ENTRY_01A", label: "VOICE LOG - S13 ENTRY 01", folder: "VOICE LOG ARCHIVE" },
    "TAPE_02.LOG": { id: "TAPE_02.LOG", labal: "TAPE_02.LOG", folder: "VOICE LOG ARCHIVE" },
    "S13_INITIAL_RECOVERY-DOC_112F": { id: "S13_INITIAL_RECOVERY-DOC_112F", label: "RECOVERY BRIEF - SPECIMEN S13 INCIDENT", folder: "Frequency 666.0" },
  };
  
  export const dossierResponses = {
    "DIREWOLF_RESCUE-DOC_78A": [
"\n>> [DIREWOLF EXTRACTION REPORT]",
"- Unit: 113th Cryo-Lancers, Frostbound Strikers",
"- Subject: Ghostpaw - Field Medic / Operative",
"- Date: ██/██/████",
"- Location: Peripheral Zone, Cryo-Station Theta-V Approach",
"\n",
">> Overview:",
"- During a routine patrol near the compound's southern ingress, Ghostpaw encountered an unexpected enemy ambush resulting in the dispersal of squad elements. Amid the confusion and disarray, operative Ghostpaw located a critically injured direwolf pup—severely mauled by hostile forces designated as “The Hollowed.” This extraction was recorded as a non-combat casualty operation with significant tactical and morale implications.",
"\n",
">> Field Observations:",
"• The pup was isolated in a narrow ice alcove, its fur matted and blood-soaked, exhibiting signs of severe lacerations.",
"• Enemy forces, utilizing low-angle suppressive fire and chemical agents, had abandoned the creature after overwhelming local defenses. Its survival was unexpected.",
"• Ghostpaw immediately provided emergency field care; stabilizing the pup with improvised trauma techniques learned during his medic training.",
"• Commander Erza, upon arrival, documented his initial disapproval—her usual stern tone softened upon witnessing his persistence and the pup's vulnerability.",
"• Subsequent drone footage later confirmed the pup's extraction under heavy enemy engagement. Erza authorized additional resources for the pup's care, recognizing the symbolic value of its rescue.",
"\n",
">> Operational Impact:",
"- The direwolf rescue not only showcased Ghostpaw's compassion and medical expertise under fire but also became a turning point in unit morale. The incident further reinforced his codename, 'Ghostpaw,' reflecting his silent determination and the eerie resemblance of his gloved hands to a dire wolf's paw.",
"- Intelligence indicated that the rescued pup might serve both as a tactical scout in small-unit operations and as an emblem of resilience for the squad.",
"- The event is now integrated into squad lore and remains a key motivator in subsequent operations. A follow-up dossier has been created for “The Dire Wolf Companion” to track its progress and any influence on field tactics.",
"\n",
">> Conclusion:",
"- The extraction operation was a success against overwhelming odds. It highlighted both the vulnerabilities inherent in frontline combat and the unexpected bonds that form amidst chaos.",
"- End of Report."],
    "LUSTRA_CHEM-USE_LOG_77B-A": [
"\n>> [INCIDENT REPORT: NIGHT FURY AMBUSH]",
"- Unit: 113th Cryo-Lancers, Frostbound Strikers",
"- Subject: Ghostpaw - Field Medic / Squad Report Writer",
"- Date: ██/██/████",
"- Location: Northern Expanse, Near Frostline Ridge",
"\n",
">> Incident Summary:",
"- During an operation designated “Night Fury,” Ghostpaw was deployed as part of a recon and extraction mission in the hostile northern expanse. An ambush by enemy forces—using both conventional ordnance and chemical distracters—shattered the initial formation. Ghostpaw's rapid field response not only saved multiple lives but also secured critical intel that later contributed to a strategic counter-offensive.",
"\n",
">> Event Chronology:",
"• As dusk descended, unit positions were illuminated by controlled bursts of Lustra, ensuring operational visibility. However, an enemy volley caught the squad off-guard. The ambush produced disorienting bursts of chemical fire, temporarily obscuring vision and hampering communication.",
"• Amidst the chaos, Ghostpaw, stationed at the forward medical post, was forced into an improvised leadership role when primary medics and radio operators were incapacitated.",
"• Displaying remarkable calm and adaptability, he initiated emergency triage while simultaneously establishing a secure forward perimeter. His silent efficiency under duress enabled him to document events in real-time using his portable Data Recorder ('DAT-BINDER-9'), as is his duty.",
"• Fragmented memories captured in his log indicate a moment of stark realization: as the enemy advanced, he witnessed an almost uncanny synchronization—enemy movements paused, and their chaos momentarily stilled—triggering an internal, almost preternatural clarity.",
"• Ghostpaw's subsequent decision to split small groups and evacuate critical wounded personnel, while simultaneously relaying enemy positions via encoded field messages, prevented further casualties. His actions were later credited as the decisive factor in maintaining unit cohesion during the assault.",
"\n",
">> Critical Observations:",
"- The ambush incident, later dubbed “Night Fury,” established Ghostpaw's reputation as not only a compassionate medic but also a tactical improvisor. His role as the squad report writer proved invaluable; his detailed logs provided high-command with clear situational analysis post-engagement.",
"- Command noted that Ghostpaw's non-verbal communication—the way his gloved, “paws-like” hands moved methodically over injured personnel—conveyed an unwavering resolve that influenced surviving members to perform beyond standard expectations.",
"- Analysis of environmental data correlated with the use of Lustra confirms that the temporary light bursts, although designed for distraction, inadvertently synchronized enemy positions, giving Ghostpaw a critical window to act.",
"\n",
">> After-Action and Recommendations:",
"- Comprehensive debriefings with surviving squad members recommended that Ghostpaw's techniques and decision-making be further studied and integrated into training modules for future emergency medics.",
"- Additional research on the psychological phenomenon observed during the ambush (“the stillness of Night Fury”) is underway to determine if it represents a temporary state of heightened situational awareness—a potential byproduct of exposure to combat stress and battlefield lighting effects.",
"\n",
">> Conclusion:",
"- The incident demonstrates that, even under extreme adversity, Ghostpaw's innate discipline and silent vigilance can pivot a collapsing operation into a controlled extraction. His documentation and actions during “Night Fury” remain a guiding example of valor and ingenuity.",
"- End of Report."
    ],
    "S13_INITIAL_RECOVERY-DOC_112F": [
"\n>> [SPECIMEN S13 RECOVERY FILE - CLASSIFIED]",
"\n",
"- Retrieval Unit: 113th Cryo-Lancers, Frostbound Strikers",
"- Oversight: Commander Erza Kael",
"- Date: ██/██/████",
"- Coordinates: ██.███°N, ██.███°W - Site VEIL-B13",
"\n",
">> Overview:",
"- During Operation STAGLIGHT, hostile forces vacated the anomalous VEIL-B13 facility. Unit was dispatched for breach and salvage, under assumption of null-life activity.",
"- Ghostpaw located an entity of uncertain bio-origin designated 'Specimen S13' in Cryo-Containment Unit B, fused to biotech growths and connected to active conduits.",
"- Specimen S13 exhibited no vital signs in traditional biometrics. However, surrounding matter resonated with low-frequency emissions and appeared to decay under observation.",
"- On extraction attempt, containment field ruptured, exposing Ghostpaw to an airborne mutagenic agent. Entity disappeared from sight during evacuation.",
">> CAPTURE OF ENTITY:",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#%%#%#%###%#####%##%#%#%###%%###%%#%%%%%%%%%%",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%####**%#####%#* -##%%###*=+*#*#*####*###%%%%%%%%",
"   %%%%%%%%%%%%%%%%%%#%%%%#####**####*+   *####***  ***#%#%#+ ##*#*###++=##**#%%%%%",
"   %%%%%%%%%%%%#%######%%##*     =*+*+*+ +**#**###* ####%%####%#*#*#+#***+#*##%%%%%",
"   %%%%%%%%%%%%%####-#****-   +++*+=-+**+++++ **#*%**%#%##%%#%########*###*###%%%%%",
"   %%%%%%%%%*##*###+  .*#***#+*++  =+=++++++***   +#*##%#%%##%%%*######*########%%%",
"   %%%%%%%%*+##*%*#+=.#*#*+#*+*   :+-:++**::- :--+= #*#%*#####%####=*#%*##*###%%%%%",
"   %%%%%%##*%:::#%%##*#+#*%#+ ........ :...::..    +  **#%*#**%%%%####%*#*#%%%%%%%%",
"   %%%%%###%:=**#*%#%%%#%### ..    ...:::....        =+++**%***%+*###*##%%%#%%%%%%%",
"   %%%%=###****%#####%##%#* +..    ..      ...     .-+-*+*****########%%%%%%@%%%%%%",
"   %%%%++##%*##*#*%*###%#*  :..    .        ..    :::+::++***%####%#%%#%%#%%%%%%%%%",
"   %%%%**##**+***#=*#*###* -..... .:.       ... .:::+::.++*####%%*%%%%%%%%%%%%%%%%%",
"   %%*%#%%#%%%**==+%%%%++*.::-.-:::-:     .::-. .::++-::+**####%%%%%%%%%%%%%%%%%%%%",
"   %%%%%%#####****=++%++++-.::+-----=:...:::==::::=-=--:+.###%###%%%%%%%%%%%%%%%%%%",
"   %%%%%%%%%%*****#*+**=+*+:.:.==:=+==::::-:+---=+==+-=+..**%##%%%#%%%%%%%%%%%%%%%%",
"   %%%%%%%%%%%*###*%*+##*#++.-.=::==*.+:-: -==--+++*--+=#*###%#%%%%%%%%%%%%%%%%%%%%",
"   %%%%%%%%%%%###***#*+#%*+:=:*..+-++*--:--=+==+***+=+=++##*#%#%%%%%%%#%%%%%%%%%%%%",
"   %%%%%%@%%%%%#*       *+*- *-+.::*+**#=--=++*+  +++=+=*#**#%##%%%%%@%%%%%%%%%%%%%",
"   %%%%%##%####.       .  -+  =+ =.*:-----#+-=++   ++++ #*#+#%%#%%%#%%%%%%%%%%%%%%%",
"   %%%%%%%*#**       .    ==     -= *----++=-+*     +**+ ****#*#%%%##%%%%%%%%%%%%%%",
"   %%%%%%%#*+  .           -    += =+.--+ + =*        ++++****######%%%#%%%%%%%%%%%",
"   %%%%%##**:  :      =*   -:       : ++    *           .*==+*+****##%%%%%%%%%%%%%%",
"   %%%%%%*+=  :.            -            :                  -:-====+######%%%%%%%%%",
"   %%%%%#*=  . .            :                            :+...       +*###%%%%%%%%%",
"   %%%%##*=    :       *    =+     .        * .          .**.            **##%#%%%%",
"   %%%%#**=.   .      #:    :# =          :=++  .       -+*:::               #*#%%%",
"   %%%%*+*=-         #*      #+      .   .-.:.        .:...###--  *            *##%",
"   %%%##+*-.        #*       #**   ++    ++  .+        =:   ##*-: **- :=*+==      #",
"   %%%%#*++        ##        #+*.  *    -##+  *+.    : +=    #* .-***#%%%%%%+=-:   ",
"   %%%%#**+ -    .#=         *     +   -#+%#  -*..=  -+=*+       =+####%%%%%%##+   ",
"   %%%%%#*+     :#     #     #=       .#%*%#  *.:.=  -.=**=      +###*%%%%%%%%%%###",
"   %%%%##++    ##    .##    :#-      .#%%%##  *...= ----* **+   .**####%#%%%%%%%%%%",
"   %%%###*+   ##    ##+     ##      .##%%#*:  +:.-+ ==+:-*.+*+  -**##%#%%%%%%%%%%%%",
"   %%%###**  #*    ##       ##      *%%%#*-.  *:-==+=.:..* ++#=  +*##%%%#%%%%%%%%%%",
"   %%%%##*+ *#    #*       #%#     #%%%%##--   =--=-:.  . # #**-  **#%%#%%%%%%%%%%%",
"   %%%%%##**#    #+      :+-.+    *%%%%%%%=-   -:-=:.    *##+*++:  -#:%#*%#%%%%%%%%",
"   %%%###*.*   .#+   .:-:.   .    *#%%%%%#:- * :-*-.     %%% ++++-  *-%##%%%#%%%%%%",
"   %%%%*#*.#  .+#...:-=.     *    *#%%%%%#=- + :*:::-   #%%% +-=++=  *+#%%%#%%%%%%%",
"   %%%###*.* ..#*:--=:.         :  #%%%%%%#- = **::.*  *%%%%-.=****=  **+*%#%%%%%%%",
"   %%%%%#-.: ..#*--=-.     =   .   *#%%%%%#  + *#:. *  #%%%%*+=****-   **%#%%%%%%%%",
"   %%#%###+:*..##--:.          -   :#%%%%%#* * =.:++*  #%%%%# *=+**+=   +#%%%%%%%%%",
"   %%%#%##-##..:##-..         -:    *#%%%%*. -  =+*+#= *  ##. --++++=+  **#%%%%%%%%",
"   %%%%#%#-%%%...###..        -     :#%%%*   = =+**+*+    ##- -+=+-++--  +#%%%%%%%%",
"   %%%#*%%#%##*+ ..####*     ..      ####    : ++++-+*    +*= =++***=++   -#%%%%%%%",
"   %%%%@%%##*#****=..#..     .     -*###     + ++**.:+     *=.-+***++==-   #%%%%%%%",
"   %%%%%%%%#######**:#+=+++   =-=*##%%%#    -= ++***=+     +++ ++*+++.==   ##%%%%%%",
"   %#%%%%%%#%##*##+++==*+=+  ==###%%%%%##   -- -*****+    =++: ++=*++--:-   *%%%%%%",
"   %%%%%#%##%%#.       =-:   +==#####%#*:   +-  ** ++=  +++++= =+=++++-:.   +#%%%%%",
"   %%%#%%%%#+:.                           . ==  +*:+*++ +***+=.--+--:--.-    *#%%%%",
"   %%%#%%%%#::#.                       :::- =- :**++++= +#***: :=+=-=:....    *#%%%",
"   %%%%%%%%%-.+#**                ==*+=+=-  -:  *+++**+ **#**: :.-+--:....    =+#%%",
"   %%%%%#@%%%%###**#*        +=++*+***+++: :-:  +*+++++ +###+=: :-::-.-..      *#%%",
"   %%%%%%%%%%%%%%%%##*##** +###*#*.##=*+:+ :-:  +*++++: .*#***=   -.-...:      +#%%",
"   %%%%%%%%%%%%%%%%%+##%## ######%%%+%+#== ::.  ++=+++=  *####*-   ......       #%%",
"   %%%%%@%%%%%%%%%%%+-%%%*=*%#%#%%%##%**-  ::: -**=-+.:  *###**==   :... .  .   *#%",
"   %%%%%%%%%%%%%%%%%%%%%%%# %%#%%%%%%%#++ .::. -*+.=-:.  *##+##*+=   . . ...    -*#",
"   %%%%%%%%%%%%%%%%%%%%%%%% #%%%%%%%#%=+- .... .** :-..  #%%%##**++        ..    *#",
"   %%%%%%%%%%%%%%%%%%%%%%%% %%%#%#%%%#*+  . .  :** ...:. *#%%#%###*+    .....    :#",
"   %%%%%%%%%%%%%%%%%%%%%%%%#%%%#%#%%%#*+       **** .... *#%%#####*++      .      *",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%##*    -   *##+ ...: :##%%%%###+*+=     ..    =",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%**   =+   ###+   .. .#%%%%%%###**+=       .   ",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#-   +*   *###+  ... ##%%%%%*#%*#*++          ",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#+   =**   *#%%*+     #*%##%%%%###**+++        ",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#+   *#*   *##%#*      ###%%%%%%%###*++=       ",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%*+   *#*   +##%%*+     *##%%#%%%%%###*++=      ",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#*    ###   *#%%##+     +*%%%%%%%%%%###**+=     ",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%**   *##*   *#%%%%*=    +#%%%%%%%%%%%###*#+=    ",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#=   *###+  *#%%%%%#     *#%%%%%%%%%%%%###*+=   ",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#*    ##%#+  *%%%%%*#*    *#%%%%%%%%%%%%##***+   ",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#*   ##%%#+  *%%%%%%%#    +#%%%%%%%%%%%%%####*+  ",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#+   *%%##*  +%%%=%%+##   :##%%%%%%%%%%%%%%#***- ",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%*+    #%%#%+  *%%%%%%%%#    *#%%%%%%%%%%%%%%#*#*+ ",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#*   *#%%%#+  #%%%%%%%%%*   *#%%%%%%%%%%%%%%%###+-",
"(Recovered via Drone Uplink V13-B - Captured from Ghostpaw's DAT-BINDER-9)",
"\n",
">> Experimental Findings:",
"• Ghostpaw's exposure triggered latent neurological aberrations 3 days post-incident: tremors, heightened visual field, inability to retain sleep. Standard detox failed.",
"• Entity's residue measured incompatible with current matter theory. Lustra-exposed samples rendered inert.",
"• Cryo-Vault personnel have since reported auditory phenomena at VEIL-B13. Disciplinary records pending.",
"\n",
">> Status:",
"- Ghostpaw marked as VOID-TOUCHED. Voluntarily re-enlisted under Section ██.",
"- Entity remains unrecovered. Future sightings will use Signal Tag: [S13-VEILSHADOW]",
"- END REPORT",
],
 "VOICE_S13-ENTRY_01A": [
"\n>> [LOG TYPE: AUDIO // Transcription Active]",
"\n",
"- Source: Personal Recorder - Ghostpaw",
"- Location: Quarantine Block, Theta-V Med-Bay",
"- Status: Playback",
"\n",
"'I didn't hear it, but I did. You get me? Like—when you're looking at someone screaming through the glass, but your headset's been cut. You feel it, in your gut, like something you shouldn't understand...but do.'",
"[5-second silence]",
"'That thing wasn't dead. S13. No heartbeat, no breath, but it looked at me. I didn't blink. Couldn't. Couldn't even look away. Like my head was nailed in place.'",
"[soft static, faint mechanical clicking]",
"'I think it took something when it vanished. I haven't figured out what yet. I'm still here, right? Still me. But the more I talk to you, the more I wonder if the me you're hearing isn't the same one I remember being.'",
"- [Transcription ends]"
],
  "TAPE_02.LOG": [
"\n>> [LOG TYPE: AUDIO // Transcription Active]",
"- FILE NAME: TAPE_02.LOG",
"- ENTRY CLASS: CRYO-CHAMBER // PERSONAL AUDIO TAPE RECORD",
"- DURATION: 90 minutes (2 sides)",
"- FILE ORIGIN: SQUAD-113 // EZRA // FIELD DECK ARCHIVE",
"\n",
"┌────────────────────────────────────────────────────────────┐",
"│ For the rookie who curled up like a fox the night it fell. │",
"│   'Erza's Mix - GhostFox you owe me a cup of hot cocoa.'   │",
"└────────────────────────────────────────────────────────────┘",
"\n",
"───────────────────────",
"▶ SIDE A: WARM HANDS, COLD WORLD",
"───────────────────────",
">> VOICE NOTE 001:",
"- 'Hey Pup. You were asleep when I recorded this—figures. First snowfall of the season and you're curled up like a fox in the medbay. This one always reminded me of that awkward tenderness you carry around like a backpack. Heavy but real.'",
"> TRK 001: Mitski – “First Love / Late Spring”",
"> TRK 002: Radiohead – “No Surprises”",
"> TRK 003: The Rah Band – “Messages from the Stars (Sped Up)”",
"\n",
">> VOICE NOTE 002:",
"- 'Cleaning day at Outpost Theta, remember? You were grumbling about mopping the corridor floors, and I cranked this up so loud the command feed got static. Worth it.'",
"> TRK 004: The Crane Wives – “The Moon Will Sing”",
"> TRK 005: Arctic Monkeys – “Do I Wanna Know?”",
"> TRK 006: Mitski – “Heat Lightning”",
"\n",
">> VOICE NOTE 003:",
"- 'You used to say thunder didn't scare you. Not till that one night in Sector 9 when the ceiling cracked open. You held onto that pup like she was the only solid thing left. You were shaking, Ghost. You didn't say a word, but I saw it.'",
"> TRK 007: Gorillaz – “Empire Ants” (feat. Little Dragon)",
"> TRK 008: The Cranberries – “Dreams”",
"> TRK 009: My Chemical Romance – “I Don't Love You”",
"\n",
">> VOICE NOTE 004:",
"- 'Not everything ends clean, Pup. Some things rot slow and beautiful. Like roses in frost. Side B's where the real cocoa kicks in.'",
"\n",
"────────────────────────────",
"▶ SIDE B: I'LL BE BACK WHEN THE SNOW MELTS",
"────────────────────────────",
"> TRK 010: Nirvana – “All Apologies”",
">> VOICE NOTE 005:",
"- 'For the fights we never had the time to have. I hope you scream this one into the void sometime. Just once.'",
"> TRK 011: The Crane Wives – “Easier”",
"> TRK 012: TV Girl – “Lovers Rock”",
"> TRK 013: Radiohead – “How to Disappear Completely”",
"\n",
">> VOICE NOTE 006:",
"- 'Mission Delta-113. The one you wrote up after we lost Kael. You never cried in front of the squad. But you recorded your log at 3AM and forgot to mute the static. I kept that tape. I always knew.'",
"> TRK 014: Arctic Monkeys – “505”",
"> TRK 015: Mitski – “Last Words of a Shooting Star”",
"> TRK 016: The Crane Wives – “Never Love an Anchor”",
"\n",
">> VOICE NOTE 007:",
"- 'Maybe this one's for me. I tried to hold everyone together, didn't I? Guess I forgot how to be held too.'",
"> TRK 017: My Chemical Romance – “The Ghost of You”",
"> TRK 018: The Rah Band – “Clouds Across the Moon”",
"\n",
">> VOICE NOTE 008 (FINAL):",
"- 'If you're hearing this, it means you're still breathing. I'm not asking you to move on, Ghost. I'm just asking you to keep walking. One more mile. For me. For us. I'll be back when the snow melts, and we can finally have that cup of cocoa.'",
"\n",
"[1.4s of silence… tape hiss intensifies slightly]",
"\n",
"> GHOSTPAW (very soft, barely picked up by mic):",
"- '...Snow's not melting, Ez. Not here. Not ever.'",
"\n",
"[tape clicks. auto-loop re-engaged.]"
  ],
  "TAPE_ERZA_XX17": [
"\n>> [DOSSIER: ERZA’S MIX TAPE – LEGACY OF COCOA & COURAGE]",
"- Subject: Audio Cassette labeled 'Erza's Mix – Ghostpaw, You Owe Me a Cup of Cocoa'",
"- Origin: Field Deck Archive, Unit 113 – Recorded during Operation White Echo.",
"- Recovery: Tape was found in a storage locker near the medbay following a communication blackout.",
"- Condition: Exterior shell worn but legible, hand-scribbled notes in Erza’s neat scrawl; scent faintly of lavender and cordite.",
"\n",
">> Overview:",
"- The tape contains a 90-minute mixtape divided into two sides interlaced with voice notes.",
"- Erza’s voice is tender yet commanding—her words are as much a reminder of home as they are a rallying cry.",
"- The mixtape serves as both a morale booster and a subtle reprimand, a reminder of shared hardships and promises kept, especially in moments when the cold seems overwhelming.",
"\n",
">> Content Analysis:",
"- Voice notes reference specific incidents: a spilled cocoa incident at Outpost Theta, the comfort of shared laughter in bleak times, and quiet moments of mutual reassurance amid chaos.",
"- Musical selections are predominantly from pre-2000 indie and alternative bands, interwoven with modern influences (e.g., Arctic Monkeys, Radiohead, My Chemical Romance, Nirvana, Gorillaz, Mitski, TV Girl, The Crane Wives, The Rah Band).",
"- Special note: The tape ends on a fragment of static in which Erza’s fading voice wishes Ghostpaw safe passage home.",
"\n",
">> Operational Impact:",
"- The mixtape has become an unofficial morale emblem. Unit members recall it during downtimes.",
"- It’s used in after-action reviews as a reminder that despite the harshness of our environment, remnants of warmth and familial care persist.",
"- Further analysis of voice timbre suggests hidden layered messages; these are slated for decryption by Field Tech Ops.",
"\n",
">> Conclusion:",
"- Erza’s Mix Tape is archived under personal logs—an enduring reminder of the bonds forged in frost and fire. It serves as both a personal memoir and a covert directive: “Keep moving forward. Never forget where you came from.”",
"\n",
">> End of Dossier."
  ],
  "OMPF_GHOSTPAW_001A": [
"\n>> [OPERATIVE DOSSIER: GHOSTPAW]",
"- Codename: Ghostpaw",
"- Official Name: [REDACTED]",
"- Physical Characteristics:",
"• Height: ~5’4” (162 cm)",
"• Build: Slender, sleeper build; deceptively frail yet resilient.",
"• Hair: Once uncolored—now white; a dyeing technique learned under the tutelage of Commander Erza.",
"• Skin: Pale, almost translucent in the cold, marked by black, tendril-like scars that flare under duress.",
"• Eyes: Piercing, with an intensity that betrays both trauma and quiet determination.",
"\n",
"- Psychological Profile:",
"• Temperament: Typically stoic, almost unnervingly silent; rarely expresses emotion aloud, yet inner turmoil is evident in fragmented logs.",
"• Notable Traits: Remarkable under-fire calm; an inherent empathy for lost souls and wounded animals.",
"• Background: Drafted from impoverished origins, forced into military service at a young age; evolved into an exceptional combat medic—and squad report writer.",
"\n",
"- Operational Notes:",
"• Earned the codename “Ghostpaw” due to his ghost-like silence on patrol and the uncanny resemblance of his gloved hands to a dire wolf pup's.",
"• Frequently tasked with sensitive, lone operations; his logs reveal a dichotomy between a hardened exterior and deeply felt, hidden vulnerabilities.",
"\n",
">> End of Report."
  ],
  "OMPF_ERZA_002B": [
"\n>> [OPERATIVE DOSSIER: ERZA “CRIMSON WARDEN” ROSEDANE]",
"- Codename: Crimson Warden",
"- Official Name: Erza Rosedane",
"- Physical Characteristics:",
"• Height: ~5’8” (173 cm)",
"• Build: Athletic and resolute; carries herself with an air of authority tempered by genuine care.",
"• Hair: Dyed in shades of red or pink; bold, emblematic of her fiery spirit and unyielding determination.",
"• Complexion: Warm, with a slight hint of scar tissue from past battles; her gaze holds both softness and steely resolve.",
"\n",
"- Role & Personal Attributes:",
"• Primary Squad Commander of the Frostbound Strikers.",
"• Acts as both a mentor and a big-sister figure to her subordinates, especially Ghostpaw.",
"• Known for her dry wit, unsentimental discipline, and unwavering loyalty.",
"• Established a tradition of “cocoa duty” as both a reprimand and a bonding ritual—a small comfort in a freezing war zone.",
"\n",
"- Operational Impact:",
"• Her mixtapes are a blend of nostalgia and covert pep-talks; tracks interlaced with voice logs that motivate, mock, and console.",
"• Believed to hold unrecorded secrets pertaining to unexplained phenomena on the field; her logs will be declassified upon future inquiry.",
"\n",
">> End of Report."
  ],
  "COMP_DIREWOLF_114X": [
">> [COMPANION DOSSIER: “COMET” THE DIREWOLF]",
"- Common Name: Comet",
"- Species: Juvenile Arctic Direwolf",
"- Estimated Age: ~8 months",
"- Physical Profile:",
"• Weight: Approx. 31.2 kg",
"• Distinctive Markings: Notable burn scar across right foreleg; patchy fur exhibiting frost damage.",
"• Build: Lean, agile; typical of high-arctic subspecies adapted to extreme cold.",
"\n",
"- Behavioral Observations:",
"• Exhibits a profound attachment to Operative Ghostpaw; follows him consistently on patrols.",
"• Displays a protective posture, particularly when Ghostpaw is in distress—often growls softly at approaching threats.",
"• Accepts only food directly administered by Ghostpaw or through authorized care channels.",
"• Responds visibly to musical cues from Erza’s mixtape—tail wagging, ear pricks—indicating a possible deep empathic link.",
"\n",
"- Operational Significance:",
"• Recovered during the direwolf extraction operation following an enemy ambush; served as an emblem of resilience.",
"• Has since been designated as the Mascot-Class Companion for Unit 113, symbolizing the will to survive against overwhelming odds.",
"• Observations suggest potential utility for reconnaissance missions due to heightened sensory acuity.",
"\n",
">> End of Report.",
  ],
  "BASE_ICEHALLOW_003C": [
"\n>> [BASE DOSSIER: CRYO CHAMBER GRID – ICEHALLOW BASE]",
"- Designation: IceHallow",
"- Location: Northern Expanse, Sector Theta-V, on the frostbound fringe of the known perimeter.",
"- Date of Last Renovation: ██/██/20██ (Per maintenance cycle report)",
"- Structural Integrity: Reinforced cryo-sealed chambers with multi-layered insulation; primary exterior composed of reinforced alloy and cryo-concrete.",
"\n",
">> Overview:",
"- IceHallow Base is the sole forward operating facility for the 113th Cryo-Lancers. Isolated by severe winter storms and constant snow drifts, it remains operational via automated supply routes and satellite field relays.",
"- The base comprises multiple vertically oriented chambers: Cryo-Decontamination, Medical Quarters, Armory, Surveillance Hub, and a central Command Bridge located deep beneath several layers of frost.",
"- Due to its extreme isolation, personnel rely on redundant communication networks and manual overrides for critical operations.",
"\n",
">> Infrastructure & Facilities:",
"> **Cryo Chamber Grid:**  ",
"- Network of interlinked chambers built into a glacier-like structure. Serves as the living quarters and operational nerve center.",
"- Temperature maintained below -40°C during winter assaults; equipped with automated cryogenic support systems.",
"> **Command Bridge:**  ",
"- Located on the lowest level; equipped with analog interfaces and classified cryptographic terminals.",
"- Houses the central data hub for coordinating maneuvers, decrypting enemy transmissions, and issuing deployment orders.",
"> **Medical & Recovery Bay:**"  ,
"- High-security medbay capable of managing biohazardous incidents and trauma under severe snow conditions.",
"- Incorporates cryo-decontamination showers and temporary containment chambers for Void-related anomalies.",
"> **External Perimeter & Access Points:**  ",
"- Limited to one major access point, heavily camouflaged by severe snow and ice accumulation.",
"- Monitored by automated directional sensors and manned by the Frostbound Strikers.",
"\n",
">> Environmental Conditions:",
"> **Severe Snowfall:**  ",
"- The base is routinely subjected to blizzard conditions, limiting aerial reconnaissance and complicating resupply efforts.",
"> **Frostbite Threat:**  ",
"- Exposure to freezing winds necessitates continuous temperature control and intermittent manual inspection.",
"> **Isolation Protocol:** " ,
"- Due to constant electromagnetic interference from high-altitude ion storms, redundant communication methods are in place. ",
"\n",
">> Operational Impact & Tactical Relevance:",
"- IceHallow Base functions as the critical outpost for launching covert recovery and reconnaissance operations, including missions into enemy-held terrain and the further investigation of Specimen S13.",
"- The combination of manual cryo-technology and forced analog command interfaces fosters an atmosphere of nostalgic resilience despite technological stagnation.",
"- Base logs indicate that personnel experience both a heightened sense of unity and individual isolation—factors that drive the squad’s reliance on personal mementos such as mixtapes and detailed voice logs.",
"\n",
">> Conclusion:",
"- IceHallow Base remains the backbone of the 113th Cryo-Lancers’ operations. It is both a fortress and a haven, meticulously maintained against the relentless assault of nature.",
"- The facility’s design embodies the necessary grit and care of a unit that endures perpetual winter—a silent guardian protecting the few who still dare to fight in a frozen world.",
"\n",
"> End of Report."
],
  };