// This file contains the dossier nodes and responses for the terminal.

/* ----------------------------- Dossier Nodes ----------------------------- */
export const dossierNodes = {
  // Cryo-Chamber Grid
  "LUSTRA_CHEM-USE_LOG_77B-A": {
    id: "LUSTRA_CHEM-USE_LOG_77B-A",
    label: "INCIDENT REPORT: NIGHT FURY AMBUSH",
    folder: "Cryo-Chamber Grid",
  },
  "BASE_ICEHALLOW_003C": {
    id: "BASE_ICEHALLOW_003C",
    label: "BASE ICEHALLOW - 003C",
    folder: "Cryo-Chamber Grid",
  },
  "CYANOR_LUA_RELIGION_DOSSIER_01": {
    id: "CYANOR_LUA_RELIGION_DOSSIER_01",
    label: "CYANOR LUA RELIGION DOSSIER 01",
    folder: "Cryo-Chamber Grid",
  },

  // Dossier Compilation
  "DIREWOLF_RESCUE-DOC_78A": {
    id: "DIREWOLF_RESCUE-DOC_78A",
    label: "DIREWOLF EXTRACTION REPORT",
    folder: "Dossier Compilation",
  },
  "SIRO_0051-AUDIO-REV3": {
    id: "SIRO_0051-AUDIO-REV3",
    label: "SIRO_0051-AUDIO-REV3",
    folder: "Dossier Compilation",
  },
  "TAPE_ERZA_XX17": {
    id: "TAPE_ERZA_XX17",
    label: "TAPE_ERZA_XX17",
    folder: "Dossier Compilation",
  },
  "OMPF_GHOSTPAW_001A": {
    id: "OMPF_GHOSTPAW_001A",
    label: "OMPF_GHOSTPAW_001A",
    folder: "Dossier Compilation",
  },
  "OMPF_ERZA_002B": {
    id: "OMPF_ERZA_002B",
    label: "OMPF_ERZA_002B",
    folder: "Dossier Compilation",
  },
  "COMP_DIREWOLF_114X": {
    id: "COMP_DIREWOLF_114X",
    label: "COMP_DIREWOLF_114X",
    folder: "Dossier Compilation",
  },
  "CRX7_NOCTIS-DOSSIER_044V": {
    id: "CRX7_NOCTIS-DOSSIER_044V",
    label: "CRX7_NOCTIS-DOSSIER_044V",
    folder: "Dossier Compilation",
  },

  // Voice Log Archive
  "VOICE_S13-ENTRY_01A": {
    id: "VOICE_S13-ENTRY_01A",
    label: "VOICE LOG - S13 ENTRY 01",
    folder: "VOICE LOG ARCHIVE",
  },
  "TAPE_02.LOG": {
    id: "TAPE_02.LOG",
    label: "TAPE_02.LOG",
    folder: "VOICE LOG ARCHIVE",
  },

  // Frequency 666.0
  "S13_INITIAL_RECOVERY-DOC_112F": {
    id: "S13_INITIAL_RECOVERY-DOC_112F",
    label: "RECOVERY BRIEF - SPECIMEN S13 INCIDENT",
    folder: "Frequency 666.0",
  },
  "S13-B13-LOG_0421A": {
    id: "S13-B13-LOG_0421A",
    label: "S13-B13-LOG_0421A",
    folder: "Frequency 666.0",
  },
};

/* ---------------------------- Dossier Responses ---------------------------- */
export const dossierResponses = {
  /* ------------------------- Cryo-Chamber Grid ------------------------- */
  "LUSTRA_CHEM-USE_LOG_77B-A": [
"\n>> [INCIDENT REPORT: NIGHT FURY AMBUSH]",
"- Unit: 113th Cryo-Lancers, Frostbound Strikers",
"- Subject: Ghostpaw - Field Medic / Squad Report Writer",
"- Date: ██/██/████",
"- Location: Northern Expanse, Near Frostline Ridge",
"\n",
">> Incident Summary:",
"- During an operation designated “Night Fury,” Ghostpaw was deployed as part of a recon and extraction mission in the hostile northern expanse. An ambush by enemy forces—using both conventional ordnance and chemical distracters—shattered the initial formation. Ghostpaw's rapid field response not only saved multiple lives but also secured critical intel that later contributed to a strategic counter-offensive.",
"\n",
">> Event Chronology:",
"• As dusk descended, unit positions were illuminated by controlled bursts of Lustra, ensuring operational visibility. However, an enemy volley caught the squad off-guard. The ambush produced disorienting bursts of chemical fire, temporarily obscuring vision and hampering communication.",
"• Amidst the chaos, Ghostpaw, stationed at the forward medical post, was forced into an improvised leadership role when primary medics and radio operators were incapacitated.",
"• Displaying remarkable calm and adaptability, he initiated emergency triage while simultaneously establishing a secure forward perimeter. His silent efficiency under duress enabled him to document events in real-time using his portable Data Recorder ('DAT-BINDER-9'), as is his duty.",
"• Fragmented memories captured in his log indicate a moment of stark realization: as the enemy advanced, he witnessed an almost uncanny synchronization—enemy movements paused, and their chaos momentarily stilled—triggering an internal, almost preternatural clarity.",
"• Ghostpaw's subsequent decision to split small groups and evacuate critical wounded personnel, while simultaneously relaying enemy positions via encoded field messages, prevented further casualties. His actions were later credited as the decisive factor in maintaining unit cohesion during the assault.",
"\n",
">> Critical Observations:",
"- The ambush incident, later dubbed “Night Fury,” established Ghostpaw's reputation as not only a compassionate medic but also a tactical improvisor. His role as the squad report writer proved invaluable; his detailed logs provided high-command with clear situational analysis post-engagement.",
"- Command noted that Ghostpaw's non-verbal communication—the way his gloved, “paws-like” hands moved methodically over injured personnel—conveyed an unwavering resolve that influenced surviving members to perform beyond standard expectations.",
"- Analysis of environmental data correlated with the use of Lustra confirms that the temporary light bursts, although designed for distraction, inadvertently synchronized enemy positions, giving Ghostpaw a critical window to act.",
"\n",
">> After-Action and Recommendations:",
"- Comprehensive debriefings with surviving squad members recommended that Ghostpaw's techniques and decision-making be further studied and integrated into training modules for future emergency medics.",
"- Additional research on the psychological phenomenon observed during the ambush (“the stillness of Night Fury”) is underway to determine if it represents a temporary state of heightened situational awareness—a potential byproduct of exposure to combat stress and battlefield lighting effects.",
"\n",
">> Conclusion:",
"- The incident demonstrates that, even under extreme adversity, Ghostpaw's innate discipline and silent vigilance can pivot a collapsing operation into a controlled extraction. His documentation and actions during “Night Fury” remain a guiding example of valor and ingenuity.",
"- End of Report."
    ],
  "BASE_ICEHALLOW_003C": [
"\n>> [BASE DOSSIER: CRYO CHAMBER GRID – ICEHALLOW BASE]",
"- Designation: IceHallow",
"- Location: Northern Expanse, Sector Theta-V, on the frostbound fringe of the known perimeter.",
"- Date of Last Renovation: ██/██/20██ (Per maintenance cycle report)",
"- Structural Integrity: Reinforced cryo-sealed chambers with multi-layered insulation; primary exterior composed of reinforced alloy and cryo-concrete.",
"\n",
">> Overview:",
"- IceHallow Base is the sole forward operating facility for the 113th Cryo-Lancers. Isolated by severe winter storms and constant snow drifts, it remains operational via automated supply routes and satellite field relays.",
"- The base comprises multiple vertically oriented chambers: Cryo-Decontamination, Medical Quarters, Armory, Surveillance Hub, and a central Command Bridge located deep beneath several layers of frost.",
"- Due to its extreme isolation, personnel rely on redundant communication networks and manual overrides for critical operations.",
"\n",
">> Infrastructure & Facilities:",
"> **Cryo Chamber Grid:**  ",
"- Network of interlinked chambers built into a glacier-like structure. Serves as the living quarters and operational nerve center.",
"- Temperature maintained below -40°C during winter assaults; equipped with automated cryogenic support systems.",
"> **Command Bridge:**  ",
"- Located on the lowest level; equipped with analog interfaces and classified cryptographic terminals.",
"- Houses the central data hub for coordinating maneuvers, decrypting enemy transmissions, and issuing deployment orders.",
"> **Medical & Recovery Bay:**"  ,
"- High-security medbay capable of managing biohazardous incidents and trauma under severe snow conditions.",
"- Incorporates cryo-decontamination showers and temporary containment chambers for Void-related anomalies.",
"> **External Perimeter & Access Points:**  ",
"- Limited to one major access point, heavily camouflaged by severe snow and ice accumulation.",
"- Monitored by automated directional sensors and manned by the Frostbound Strikers.",
"\n",
">> Environmental Conditions:",
"> **Severe Snowfall:**  ",
"- The base is routinely subjected to blizzard conditions, limiting aerial reconnaissance and complicating resupply efforts.",
"> **Frostbite Threat:**  ",
"- Exposure to freezing winds necessitates continuous temperature control and intermittent manual inspection.",
"> **Isolation Protocol:** " ,
"- Due to constant electromagnetic interference from high-altitude ion storms, redundant communication methods are in place. ",
"\n",
">> Operational Impact & Tactical Relevance:",
"- IceHallow Base functions as the critical outpost for launching covert recovery and reconnaissance operations, including missions into enemy-held terrain and the further investigation of Specimen S13.",
"- The combination of manual cryo-technology and forced analog command interfaces fosters an atmosphere of nostalgic resilience despite technological stagnation.",
"- Base logs indicate that personnel experience both a heightened sense of unity and individual isolation—factors that drive the squad’s reliance on personal mementos such as mixtapes and detailed voice logs.",
"\n",
">> Conclusion:",
"- IceHallow Base remains the backbone of the 113th Cryo-Lancers’ operations. It is both a fortress and a haven, meticulously maintained against the relentless assault of nature.",
"- The facility’s design embodies the necessary grit and care of a unit that endures perpetual winter—a silent guardian protecting the few who still dare to fight in a frozen world.",
"\n",
"> End of Report."
],
  "CYANOR_LUA_RELIGION_DOSSIER_01": [
"\nDoctrine of Cyanor & Lua’Theris",
">> Overview",
"- Ghostpaw’s sect venerates the cosmic dance of the sun and moon as a living metaphor for hope and loss. In its sacred lore, Cyanor (the Radiant Sun) and Lua’Theris (the Silver Moon) are twin deities whose interplay shapes destiny. An eclipse is regarded as the ultimate symbol of their union and rebirth; adherents teach that when the moon shadows the sun, the world is cleansed for a new dawn. This belief melds scientific observation of celestial events with ancient myth: Cyanor is revered as “the bestower of light and life to the totality of the cosmos” , while Lua’Theris governs the cycle of disappearance and reappearance, linking death to rebirth . The resulting faith feels both primordial and rational – as though temple priests chart star charts as holy scripture, and satellite data as divine prophecy. Central to the doctrine is a vision of transformation: Ghostpaw and fellow adepts see their own struggles reflected in the sky, interpreting darkness as temporary and each sunrise as a promise of renewal.",
"\n",
">> Doctrine",
"- Cyanor–Lua worship is built on a clear set of tenets, blending symbolism with cosmic facts:",
"- Cyanor, the Radiant King: Cyanor is identified with the physical sun – source of energy and justice. Priests teach that its unblinking light reveals truth and enforces cosmic order, echoing ancient solar cults. The sun’s path is charted as a daily “circadian passage” through upper and lower realms . Cyanor’s rays are said to penetrate the “void of despair,” kindling hope in the faithful.",
"- Lua’Theris, the Silver Matron: Lua’Theris embodies the moon’s phases. Her cycle is viewed as a mirror of life and death; when Lua’Theris wanes and disappears, it carries souls to the “Moon Realm,” and when she reappears it heralds rebirth . She is a guardian of memory – the keeper of lost loved ones – and the guide for transformation. The sect equates the waxing moon with the waxing soul: loss that gradually gives way to new light.",
"- The Shattering of Lua’Theris: Recent dogma incorporates the 'Wound of the Matron'—the great crack visible across Lua’Theris' surface. It is taught that a forbidden act of hubris shattered part of her form, scattering divine dust into a ring around the world of Arkana. This dust ring is said to be both a reminder of humanity’s arrogance and a lingering source of blessings and curses. Some sects whisper that the crack was caused by an ancient experiment to harness the divine, perhaps linked to the abominations like S13. The dust, called 'Theran Ash,' is used ceremonially but also feared.",
"- Cosmic Balance: Together, Cyanor and Lua’Theris form a perfect duality. Where Cyanor brings illumination, Lua’Theris governs night and mystery, and both are necessary. Adherents believe the interplay of light (hope) and darkness (loss) is cyclical and never final. This balances strict “sunlight justice” with compassionate lunar mercy, a doctrine that Ghostpaw interprets as meaning even the darkest trials ultimately yield wisdom and renewal.",
"- Void of Origin: A subtle but crucial doctrine (only hinted in sanctioned texts) is that the Void – a primordial emptiness – lies beyond the twins. In public myth, the Void is described only as a space of potential. In private, some mystics whisper that it represents loss so profound that only the twin deities together can heal it, drawing hope from cosmic sacrifice.",
"- These beliefs are reinforced by sacred writings and pictographs found on ruins. The sect’s scripture blends astronomical charts with allegory, as if astronomy textbooks were written in poetic verse. For example, one catechism notes that as the eclipse aligns Sun and Moon, it symbolizes the union of grief and hope into enlightenment – a doctrine that Ghostpaw often cites during candlelit prayers.",
"\n",
">> Rituals and Observances",
"- Adherents mark both solar and lunar events with ceremonies that echo their doctrine:",
"- Dawn Commencement (Hailing Cyanor): Every morning begins with facing the eastern sky. The first light of Cyanor is greeted with silence or chanted hymns. This daily rite reinforces that each sunrise is a deliverance from night’s sorrows.",
"- Lunar Vigil (Honoring Lua): On the full and new moon nights, believers hold midnight vigils. They light lamps in memory of those passed, asking Lua’Theris to guide departed souls and foster renewal. These vigils are solemn: according to sect lore, as the moon waxes the community’s hope waxes too.",
"- Eclipse Festivals: Solar and lunar eclipses are the holiest events. During an eclipse, congregations gather in ceremonial silence, viewing it as an auspicious convergence. Texts command that no new tasks be undertaken in the “three days of darkness,” mirroring ancient taboo practises . Instead, the faithful fast and meditate, believing that the eclipse foreshadows transformation.",
"- Astral Calendar: The sect maintains a detailed lunar-solar calendar. Just as ancient cultures built monuments aligned to solstices and equinoxes, Cyanor-Lua temples are oriented so that at key dates (e.g. summer/winter solstice, the Blood Moon, etc.) shafts of light pierce chambers, symbolizing divine insight . Ghostpaw’s notes indicate that these astronomical observations serve both spiritual and practical purposes – binding community life to celestial rhythm and scientific phenomena.",
"- Ritual Arts: Worship includes crafting eclipse mandalas, reciting psalms about light piercing darkness, and naming children after solar/lunar epithets. Even mundane technologies (like solar panels) are sometimes seen as gifts from Cyanor. This blend of reverence and realism marks the faith as deeply intertwined with both myth and science.",
"\n",
">> Forbidden Addendum",
"- Appendix XV: Cryptic Notes (Class. Ω - Memetic ⚠) – Partial transcript",
<GlitchText text="The forbidden addendum is scrawled in faded ink and erratic script. It bluntly identifies “Cyanor X1” as the hidden origin of the Void: the twin of Cyanor that collapsed into a black hole. It describes how Cyanor and Cyanor X1 once revolved together as a binary star system – a concept familiar to science (a “system of two stars orbiting each other” ). In this mythic footnote, the Void is said to be born from their final cataclysm. Disturbingly, the text cites recent physics: it notes that modern astronomers have detected gravitational waves from merging black holes  (implying such events, long concealed in myth, truly reshape the cosmos)." />,
<GlitchText text="The manuscript posits that Cyanor X1 is about the same mass as Cyanor (comparable to 20–30 Suns) and that their union released stupendous energy, aligning with LIGO observations of ~3 solar masses converted into gravitational radiation. The Void, it claims, is not absence but a remnant of a divine collapse—a wound in spacetime itself, forever orbiting Arkana, a silent watcher beyond reach but never beyond consequence." />,
"\n",
"[End of Document]"
    ],

  /* ------------------------- Dossier Compilation ------------------------- */  
  "DIREWOLF_RESCUE-DOC_78A": [
"\n>> [DIREWOLF EXTRACTION REPORT]",
"- Unit: 113th Cryo-Lancers, Frostbound Strikers",
"- Subject: Ghostpaw - Field Medic / Operative",
"- Date: ██/██/████",
"- Location: Peripheral Zone, Cryo-Station Theta-V Approach",
"\n",
">> Overview:",
"- During a routine patrol near the compound's southern ingress, Ghostpaw encountered an unexpected enemy ambush resulting in the dispersal of squad elements. Amid the confusion and disarray, operative Ghostpaw located a critically injured direwolf pup—severely mauled by hostile forces designated as “The Hollowed.” This extraction was recorded as a non-combat casualty operation with significant tactical and morale implications.",
"\n",
">> Field Observations:",
"• The pup was isolated in a narrow ice alcove, its fur matted and blood-soaked, exhibiting signs of severe lacerations.",
"• Enemy forces, utilizing low-angle suppressive fire and chemical agents, had abandoned the creature after overwhelming local defenses. Its survival was unexpected.",
"• Ghostpaw immediately provided emergency field care; stabilizing the pup with improvised trauma techniques learned during his medic training.",
"• Commander Erza, upon arrival, documented his initial disapproval—her usual stern tone softened upon witnessing his persistence and the pup's vulnerability.",
"• Subsequent drone footage later confirmed the pup's extraction under heavy enemy engagement. Erza authorized additional resources for the pup's care, recognizing the symbolic value of its rescue.",
"\n",
">> Operational Impact:",
"- The direwolf rescue not only showcased Ghostpaw's compassion and medical expertise under fire but also became a turning point in unit morale. The incident further reinforced his codename, 'Ghostpaw,' reflecting his silent determination and the eerie resemblance of his gloved hands to a dire wolf's paw.",
"- Intelligence indicated that the rescued pup might serve both as a tactical scout in small-unit operations and as an emblem of resilience for the squad.",
"- The event is now integrated into squad lore and remains a key motivator in subsequent operations. A follow-up dossier has been created for “The Dire Wolf Companion” to track its progress and any influence on field tactics.",
"\n",
">> Conclusion:",
"- The extraction operation was a success against overwhelming odds. It highlighted both the vulnerabilities inherent in frontline combat and the unexpected bonds that form amidst chaos.",
"- End of Report."
    ],
  "SIRO_0051-AUDIO-REV3": [
"[00:00] [RECORDING START – COMMS PACK A-9 ACTIVE][ENVIRONMENT: Blizzard overhead, metallic groaning, deep structural thumps.]",
"Erza (chuckling): 'Operation: Comet's Birthday is go. Find mash, find broth, make it a feast fit for a queen.'",
"Lily (grinning): 'Gonna make the best damn dog cake this tundra’s ever seen.'",
"Kael (snorting): 'If we don't freeze our asses off first.'",
"Ghostpaw (quiet, almost amused): 'Ambient temperature: minus twenty-four degrees. Freezing is likely.'",
"Mira (adjusting scanner): 'Supplies should be clustered in Annex B. About twenty meters north.'",
"[00:50] [FOOTSTEPS CRUNCHING ON HARD ICE]",
"Erza (muttering): 'Keep eyes peeled, pups.'",
"Kael (loud): 'Eyes are peeled. Balls are frozen. Let’s move.'",
"Ghostpaw (deadpan): 'Recommend insulating layers.'",
"Lily (laughing): 'Oh look, he jokes now.'",
"[01:30] [CREW ENTERS ANNEX B]",
"Mira (pointing): 'That crate stack. Top left—food grade markings.'",
"Kael (grinning): 'Hell yeah, jackpot. Move your asses!'",
"[WOODEN CRATE SPLINTERS UNDER KAEL'S KICK]",
"Lily (reaching inside): 'Score! Broth packs, dried meat, kibble bags… ooh, some freeze-dried berries too!'",
"Ghostpaw (quietly pleased): 'Comet will enjoy high caloric density.'",
"Erza (warm): 'She deserves it. My best girl.'",
"[02:20] [RUSTLING OF SUPPLIES; BAGS THUMPING ON FLOOR]",
"Kael (smirking): 'Dog gets better birthday food than we get rations. Not jealous at all.'",
"Ghostpaw (awkward, but trying): 'You can share a berry… if you want.'",
"Lily (laughs, ruffling his hood): 'You’re a good boy, Ghostpaw.'",
"Kael (mock scandalized): 'Shit, Lily, you can't just say that.'",
"Erza (grinning): 'Let’s get cooking after we sweep the back. Can't have surprises during the party.'",
"[03:15] [DEEP STRUCTURAL GROAN]",
"Mira (pausing): 'There’s… something behind the storage crates.'",
"Ghostpaw (frowning slightly): 'Shape irregularity. Non-standard.'",
"Kael (grunting as he shoves crates): 'Motherfucker, what is buried under—'",
"[CRATES SLIDE; REVEAL SMALL STEEL SIDE DOOR]",
"Lily (whispering): 'What the hell…?'",
"Erza (low): 'Stay sharp.'",
"Mira (scanning): 'No alarms. Manual lock. I'll get it open.'",
"[SOFT ELECTRICAL BUZZ; PANEL CLICKS]",
"Ghostpaw (watching): 'Three seconds. Efficient.'",
"Mira (wry): 'Thanks, boss.'",
"[04:30] [SIDE DOOR CREAKS OPEN]",
"Kael (snorting): 'Ladies first? Fuck that, I'm going first.'",
"Erza (commanding): 'Move in. Tight formation.'",
"[TEAM ENTERS; FLASHLIGHTS SWEEPING]",
"Ghostpaw (whispering): 'Elevator shaft. Manual override needed.'",
"Kael (jabbing broken control panel): 'Yeah, it's fucking dead.'",
"Ghostpaw (quietly helpful): 'Emergency ladder… there.'",
"[05:50] [CLANKING AS THEY DESCEND A LADDER DOWN TO SILO FLOOR]",
"Lily (panting): 'Smells like dust and dead hopes down here.'",
"Kael (grumbling): 'Smells like fuckin' trouble.'",
"[06:30] [BOOTS HIT SILO FLOOR – METALLIC ECHO]",
"Mira (scanning): 'Large objects ahead. Cylindrical.'",
"Ghostpaw (staring upward): 'Silo launch tubes. Six hatches overhead. Snow coverage invisible from outside.'",
"Erza (stepping forward, voice grim): 'Eyes front.'",
"[LIGHTS SWEEP ACROSS THREE MASSIVE WARHEADS]",
"Kael (yelling): 'Oh, fuck me sideways. Those are nukes!'",
"Lily (whispering): 'Three. That’s enough to wipe Vorrath off the map… twice.'",
"Ghostpaw (flatly): 'Each ARB-9X unit rated at two hundred kilotons. Effective elimination range: entire primary continent.'",
"Mira (wide-eyed): 'Hidden under food crates…'",
"Kael (pacing fast): 'Fucking hell. Fuck. Fuck. We’re standing next to goddamn death.'",
"Erza (tight voice): 'No comms. No calls. We keep this shit silent.'",
"Lily (steady): 'We came here for Comet. We leave wit Comet’s birthday intact.'",
"Ghostpaw (almost shy): '…we can still bake the cake.'",
"Kael (laughing, almost hysterical): 'You're serious? Lua'Theris, Ghostpaw.'",
"Erza (smiling softly): 'Damn right we bake it. My pups finish what they start.'",
"[08:15] [CREW RETREATS BACK UP LADDER]",
"Mira (securing hatch): 'Lock override in place. No launches today.'",
"Ghostpaw (checking ingredients): 'Broth intact. Kibble intact. Berries intact.'",
"Kael (mock serious): 'Good. I'd beat the shit out of a ghost if you lost the berries.'",
"Ghostpaw (neutral): 'Unlikely. You would lose.'",
"Kael (laughs): 'Ohhh he’s got teeth!'",
"[09:20] [BACK AT FIELD STOVE; FUEL IGNITION]",
"Erza (grinning): 'Alright, pups. Birthday cake time.'",
"Lily (handing pot): 'Ghostpaw, you're on stirring duty. Good boys get the important jobs.'",
"Ghostpaw (awkward, stirring): 'I… like cooking. Stirring is… calming.'",
"Kael (snickering): 'You’re fucking adorable, you know that?'",
"Mira (soft smile): 'He’s doing great.'",
"Erza (warm): 'She’s gonna love it. Best damn dog food cake ever baked on this frozen hellhole.'",
"Ghostpaw (quietly, under breath): 'Happy birthday, Comet.'",
"[RECORDING END]"
    ],
  "TAPE_ERZA_XX17": [
"\n>> [DOSSIER: ERZA’S MIX TAPE – LEGACY OF COCOA & COURAGE]",
"- Subject: Audio Cassette labeled 'Erza's Mix – Ghostpaw, You Owe Me a Cup of Cocoa'",
"- Origin: Field Deck Archive, Unit 113 – Recorded during Operation White Echo.",
"- Recovery: Tape was found in a storage locker near the medbay following a communication blackout.",
"- Condition: Exterior shell worn but legible, hand-scribbled notes in Erza’s neat scrawl; scent faintly of lavender and cordite.",
"\n",
">> Overview:",
"- The tape contains a 90-minute mixtape divided into two sides interlaced with voice notes.",
"- Erza’s voice is tender yet commanding—her words are as much a reminder of home as they are a rallying cry.",
"- The mixtape serves as both a morale booster and a subtle reprimand, a reminder of shared hardships and promises kept, especially in moments when the cold seems overwhelming.",
"\n",
">> Content Analysis:",
"- Voice notes reference specific incidents: a spilled cocoa incident at Outpost Theta, the comfort of shared laughter in bleak times, and quiet moments of mutual reassurance amid chaos.",
"- Musical selections are predominantly from pre-2000 indie and alternative bands, interwoven with modern influences (e.g., Arctic Monkeys, Radiohead, My Chemical Romance, Nirvana, Gorillaz, Mitski, TV Girl, The Crane Wives, The Rah Band).",
"- Special note: The tape ends on a fragment of static in which Erza’s fading voice wishes Ghostpaw safe passage home.",
"\n",
">> Operational Impact:",
"- The mixtape has become an unofficial morale emblem. Unit members recall it during downtimes.",
"- It’s used in after-action reviews as a reminder that despite the harshness of our environment, remnants of warmth and familial care persist.",
"- Further analysis of voice timbre suggests hidden layered messages; these are slated for decryption by Field Tech Ops.",
"\n",
">> Conclusion:",
"- Erza’s Mix Tape is archived under personal logs—an enduring reminder of the bonds forged in frost and fire. It serves as both a personal memoir and a covert directive: “Keep moving forward. Never forget where you came from.”",
"\n",
">> End of Dossier."
    ],
  "OMPF_GHOSTPAW_001A": [
"\n>> [OPERATIVE DOSSIER: GHOSTPAW]",
"- Codename: Ghostpaw",
"- Official Name: [REDACTED]",
"- Physical Characteristics:",
"• Height: ~5’4” (162 cm)",
"• Build: Slender, sleeper build; deceptively frail yet resilient.",
"• Hair: Once uncolored—now white; a dyeing technique learned under the tutelage of Commander Erza.",
"• Skin: Pale, almost translucent in the cold, marked by black, tendril-like scars that flare under duress.",
"• Eyes: Piercing, with an intensity that betrays both trauma and quiet determination.",
"\n",
"- Psychological Profile:",
"• Temperament: Typically stoic, almost unnervingly silent; rarely expresses emotion aloud, yet inner turmoil is evident in fragmented logs.",
"• Notable Traits: Remarkable under-fire calm; an inherent empathy for lost souls and wounded animals.",
"• Background: Drafted from impoverished origins, forced into military service at a young age; evolved into an exceptional combat medic—and squad report writer.",
"\n",
"- Operational Notes:",
"• Earned the codename “Ghostpaw” due to his ghost-like silence on patrol and the uncanny resemblance of his gloved hands to a dire wolf pup's.",
"• Frequently tasked with sensitive, lone operations; his logs reveal a dichotomy between a hardened exterior and deeply felt, hidden vulnerabilities.",
"\n",
">> End of Report."
    ],
  "OMPF_ERZA_002B": [
"\n>> [OPERATIVE DOSSIER: ERZA “CRIMSON WARDEN” ROSEDANE]",
"- Codename: Crimson Warden",
"- Official Name: Erza Rosedane",
"- Physical Characteristics:",
"• Height: ~5’8” (173 cm)",
"• Build: Athletic and resolute; carries herself with an air of authority tempered by genuine care.",
"• Hair: Dyed in shades of red or pink; bold, emblematic of her fiery spirit and unyielding determination.",
"• Complexion: Warm, with a slight hint of scar tissue from past battles; her gaze holds both softness and steely resolve.",
"\n",
"- Role & Personal Attributes:",
"• Primary Squad Commander of the Frostbound Strikers.",
"• Acts as both a mentor and a big-sister figure to her subordinates, especially Ghostpaw.",
"• Known for her dry wit, unsentimental discipline, and unwavering loyalty.",
"• Established a tradition of “cocoa duty” as both a reprimand and a bonding ritual—a small comfort in a freezing war zone.",
"\n",
"- Operational Impact:",
"• Her mixtapes are a blend of nostalgia and covert pep-talks; tracks interlaced with voice logs that motivate, mock, and console.",
"• Believed to hold unrecorded secrets pertaining to unexplained phenomena on the field; her logs will be declassified upon future inquiry.",
"\n",
">> End of Report."
    ],
  "COMP_DIREWOLF_114X": [
">> [COMPANION DOSSIER: “COMET” THE DIREWOLF]",
"- Common Name: Comet",
"- Species: Juvenile Arctic Direwolf",
"- Estimated Age: ~8 months",
"- Physical Profile:",
"• Weight: Approx. 31.2 kg",
"• Distinctive Markings: Notable burn scar across right foreleg; patchy fur exhibiting frost damage.",
"• Build: Lean, agile; typical of high-arctic subspecies adapted to extreme cold.",
"\n",
"- Behavioral Observations:",
"• Exhibits a profound attachment to Operative Ghostpaw; follows him consistently on patrols.",
"• Displays a protective posture, particularly when Ghostpaw is in distress—often growls softly at approaching threats.",
"• Accepts only food directly administered by Ghostpaw or through authorized care channels.",
"• Responds visibly to musical cues from Erza’s mixtape—tail wagging, ear pricks—indicating a possible deep empathic link.",
"\n",
"- Operational Significance:",
"• Recovered during the direwolf extraction operation following an enemy ambush; served as an emblem of resilience.",
"• Has since been designated as the Mascot-Class Companion for Unit 113, symbolizing the will to survive against overwhelming odds.",
"• Observations suggest potential utility for reconnaissance missions due to heightened sensory acuity.",
"\n",
">> End of Report.",
  ],
  "CRX7_NOCTIS-DOSSIER_044V": [
"\n>> Satellite CRX-7 “Noctis Lancea”",
"\n>> Overview",
"- CRX-7 Noctis Lancea is  dual-purpose scientific and reconnaissance satellite commissioned to survey the Arkana star system. It was launched successfully and placed into a polar orbit just outside the fractured dust ring of the gas giant Lua’Theris. The mission combines planetary science objectives with limited military observation of potential threats or anomalies in the system. Despite sustaining minor damage (see Observed Anomalies), Noctis Lancea remains fully operational and continues its scheduled survey and data-relay operations.",
"\n",
">> Technical Specifications",
"- Platform: Modular hexagonal bus frame. Built by Arkana Spaceworks under CryoTerm-V contract. Dimensions ~2.5 m × 2.5 m × 3.0 m (deployed).",
"- Mass: ~950 kg (fully fueled). Carbon-fiber composite structure with multi-layer radiation shielding.",
"- Power: Triple-array deployable solar panels (~3.2 m span each) generating ~2.4 kW at local stellar irradiance. Redundant lithium-ion battery system providing ~12 hours of reserve operation.",
"- Propulsion & Attitude Control: Hydrazine monopropellant thrusters (eight pods) for station-keeping and maneuvers; four reaction wheels for fine attitude stabilization; cold-gas micro-thrusters for desaturation and spin adjustments.",
"- Communications: High-gain X-band uplink (8.2 GHz) / Ka-band downlink (32 GHz) with encryption (CryoTerm-V cipher protocol). Typical data rate ~150 Mbps down / 10 Mbps up. Ground station link via Arkana Orbital Command; daily 2-hour communication windows scheduled.",
"- Onboard Computer: Radiation-hardened AI core (CryoTerm OS Mk VII) with autonomous navigation and fault-protection algorithms. 128-core matrix processor (quadruple-redundant systems).",
"- Payload – Sensors & Instruments:",
"- Multi-spectral imaging camera (0.35–2.0 µm, visible/near-IR) for high-resolution mapping (down to ~0.1 m at current orbit).",
"- Infrared spectrometer (2–14 µm) for thermal and compositional analysis of ring particles and moon surfaces.",
"- Laser altimeter (LIDAR) for fine-scale topography and particle-density mapping within the ring.",
"- Magnetometer and charged-particle detector suite (magnetic field intensity up to 200 µT, particle count up to 10^6 cm^-3) for space-weather and anomaly detection.",
"- Ultra-sensitive gravimetric accelerometer for microgravity field mapping (sensitivity to sub-µGal variations).",
"- Orbit: Polar orbit around Arkana’s primary (Arkana I). Perigee ~110,000 km above Lua’Theris (just outside the ring), apogee ~220,000 km. Inclination ~90°, orbital period ~36 hours. Orbit precession is synchronized to sample varying ring latitudes.",
"- Launch Details: Deployed by the Arkav-1 booster from Arkana Launch Complex-6 on 2194-07-22 UT. Achieved orbit insertion and functional check-out by 2194-08-03 UT.",
"- Mission Profile: Continuous remote sensing mode. Routine mapping of Lua’Theris’s ring and moons with scheduled station-keeping maneuvers. Data downlink twice daily; major software update maintenance performed bi-weekly. Dual mission priorities: planetary research and threat surveillance.",
"\n",
">> Mission Status",
"- Noctis Lancea has been in operation since orbital insertion in mid-2194. All primary objectives (ring surveying, atmospheric monitoring of inner moons, etc.) are ongoing according to plan. Recent system checks indicate that while the satellite sustained minor damage, its core mission capabilities remain intact. Data transmissions continue unhindered, and instrument diagnostics report nominal performance aside from noted anomalies.",
"- Operational Status: Active (≈90% nominal functionality).",
"- Power: ~92% generation efficiency (current output ~2.2 kW). Battery reserves stable; minimal power fluctuations noted.",
"- Communications: Uplink/downlink stable; effective bandwidth at ~98% nominal. No signal interruptions beyond scheduled windows.",
"- Navigation: Orbit correction (Δv ~0.05 m/s on 2195-01-15 UT) successfully realigned trajectory. Attitude control maintained within 0.02° pointing accuracy.",
"- Thermal: All temperatures within expected range; thermal control system handling radiation exposure effectively.",
"- Instrumentation: Imaging and spectrometry channels fully operational. Recent data fidelity is high; calibration performed 2195-01-10 UT for all sensors to ensure precision after the damage event.",
"\n",
">> Observed Anomalies",
"- Since deployment, the following irregularities have been logged and addressed:",
"- Solar Array Impact (2195-01-11 UT): Minor micro-meteoroid/debris collision on the port solar array. Caused a ~3 cm perforation and ~8% localized power loss. The panel’s structural integrity remains stable. Redundant power routing compensates for lost cells; no mission degradation observed beyond reduced efficiency.",
"- LIDAR Noise: Intermittent high-frequency noise spikes detected during LIDAR scans of the dust ring. Likely caused by dense particle echoes. Automated filter algorithms attenuate the noise; resulting data quality remains acceptable. No hardware malfunction detected.",
"- Thermal Spike: A transient internal temperature increase (~4°C) was recorded following a thruster burn on 2195-01-12 UT. Attributed to propellant vent heating; thermal control re-stabilized the core within minutes. All subsystems remained within safe temperature limits.",
"- Spectral Anomaly: An unexplained infrared emission band was consistently observed near the inner ring edge. The spectral signature does not match known ices or minerals. Intensity is low (~5% above background) but persistent. Flagged for priority review; categorized under “Unknown Ring Phenomenon.”",
"- Magnetometer Glitch: A brief magnetic perturbation (Δ ~0.03 mT) was detected during one orbit pass. No corresponding source identified. Could be a transient field anomaly in the ring material. All checks normal; considered non-critical.",
"- Comm Latency Spike: A 120 ms uplink latency spike on 2195-01-20 UT coincided with increased solar flare activity. System rerouted communication, resulting in no data loss. Event logged as solar-weather effect.",
"\n",
">> Ghostpaw Field Notes",
"- Logged during post-pass data analysis (Day 2195-01-21 UT, 04:17). Recorded by Ghostpaw:",
"- The void around Lua’Theris is deceptively still. I watch Noctis Lancea’s sensor feeds—nothing truly unusual beyond the anomalies listed. That cracked solar panel is a trivial wound, but even a single impact out here feels unnerving. It reminds me how small and fragile our presence is in the void.",
"- The infrared blip on the ring still catches my eye. It’s faint, almost dismissible, yet it shows up every pass in the same region. I keep it catalogued as “unknown,” but I can’t help but wonder. Is this a quirk of the ice? A hidden geothermal vent beneath? Or something else? I won’t speculate beyond the data, but I admit there’s a trace of unease in these perfect, clinical numbers.",
"- However, I remind myself that the satellite itself knows no fear—only we do. I focus on the facts: systems nominal, objectives on track. We proceed with the mission, vigilant. The silence of space is thorough and cold, but I will not be lulled. Every anomaly is accounted for; for now, we wait and watch. My Ghostpaw remains steady on the console; nothing else is required of me but to observe.",
    ],

/* ------------------------- Voice Log Archive ------------------------- */
  "VOICE_S13-ENTRY_01A": [
"\n>> [LOG TYPE: AUDIO // Transcription Active]",
"\n",
"- Source: Personal Recorder - Ghostpaw",
"- Location: Quarantine Block, Theta-V Med-Bay",
"- Status: Playback",
"\n",
"'I didn't hear it, but I did. You get me? Like—when you're looking at someone screaming through the glass, but your headset's been cut. You feel it, in your gut, like something you shouldn't understand...but do.'",
"[5-second silence]",
"'That thing wasn't dead. S13. No heartbeat, no breath, but it looked at me. I didn't blink. Couldn't. Couldn't even look away. Like my head was nailed in place.'",
"[soft static, faint mechanical clicking]",
"'I think it took something when it vanished. I haven't figured out what yet. I'm still here, right? Still me. But the more I talk to you, the more I wonder if the me you're hearing isn't the same one I remember being.'",
"- [Transcription ends]"
    ],
  "TAPE_02.LOG": [
"\n>> [LOG TYPE: AUDIO // Transcription Active]",
"- FILE NAME: TAPE_02.LOG",
"- ENTRY CLASS: CRYO-CHAMBER // PERSONAL AUDIO TAPE RECORD",
"- DURATION: 90 minutes (2 sides)",
"- FILE ORIGIN: SQUAD-113 // EZRA // FIELD DECK ARCHIVE",
"\n",
"┌────────────────────────────────────────────────────────────┐",
"│ For the rookie who curled up like a fox the night it fell. │",
"│   'Erza's Mix - GhostFox you owe me a cup of hot cocoa.'   │",
"└────────────────────────────────────────────────────────────┘",
"\n",
"───────────────────────",
"▶ SIDE A: WARM HANDS, COLD WORLD",
"───────────────────────",
">> VOICE NOTE 001:",
"- 'Hey Pup. You were asleep when I recorded this—figures. First snowfall of the season and you're curled up like a fox in the medbay. This one always reminded me of that awkward tenderness you carry around like a backpack. Heavy but real.'",
"> TRK 001: Mitski – “First Love / Late Spring”",
"> TRK 002: Radiohead – “No Surprises”",
"> TRK 003: The Rah Band – “Messages from the Stars (Sped Up)”",
"\n",
">> VOICE NOTE 002:",
"- 'Cleaning day at Outpost Theta, remember? You were grumbling about mopping the corridor floors, and I cranked this up so loud the command feed got static. Worth it.'",
"> TRK 004: The Crane Wives – “The Moon Will Sing”",
"> TRK 005: Arctic Monkeys – “Do I Wanna Know?”",
"> TRK 006: Mitski – “Heat Lightning”",
"\n",
">> VOICE NOTE 003:",
"- 'You used to say thunder didn't scare you. Not till that one night in Sector 9 when the ceiling cracked open. You held onto that pup like she was the only solid thing left. You were shaking, Ghost. You didn't say a word, but I saw it.'",
"> TRK 007: Gorillaz – “Empire Ants” (feat. Little Dragon)",
"> TRK 008: The Cranberries – “Dreams”",
"> TRK 009: My Chemical Romance – “I Don't Love You”",
"\n",
">> VOICE NOTE 004:",
"- 'Not everything ends clean, Pup. Some things rot slow and beautiful. Like roses in frost. Side B's where the real cocoa kicks in.'",
"\n",
"────────────────────────────",
"▶ SIDE B: I'LL BE BACK WHEN THE SNOW MELTS",
"────────────────────────────",
"> TRK 010: Nirvana – “All Apologies”",
">> VOICE NOTE 005:",
"- 'For the fights we never had the time to have. I hope you scream this one into the void sometime. Just once.'",
"> TRK 011: The Crane Wives – “Easier”",
"> TRK 012: TV Girl – “Lovers Rock”",
"> TRK 013: Radiohead – “How to Disappear Completely”",
"\n",
">> VOICE NOTE 006:",
"- 'Mission Delta-113. The one you wrote up after we lost Kael. You never cried in front of the squad. But you recorded your log at 3AM and forgot to mute the static. I kept that tape. I always knew.'",
"> TRK 014: Arctic Monkeys – “505”",
"> TRK 015: Mitski – “Last Words of a Shooting Star”",
"> TRK 016: The Crane Wives – “Never Love an Anchor”",
"\n",
">> VOICE NOTE 007:",
"- 'Maybe this one's for me. I tried to hold everyone together, didn't I? Guess I forgot how to be held too.'",
"> TRK 017: My Chemical Romance – “The Ghost of You”",
"> TRK 018: The Rah Band – “Clouds Across the Moon”",
"\n",
">> VOICE NOTE 008 (FINAL):",
"- 'If you're hearing this, it means you're still breathing. I'm not asking you to move on, Ghost. I'm just asking you to keep walking. One more mile. For me. For us. I'll be back when the snow melts, and we can finally have that cup of cocoa.'",
"\n",
"[1.4s of silence… tape hiss intensifies slightly]",
"\n",
"> GHOSTPAW (very soft, barely picked up by mic):",
"- '...Snow's not melting, Ez. Not here. Not ever.'",
"\n",
"[tape clicks. auto-loop re-engaged.]"
    ],

/* ------------------------- Frequency 666.0 ------------------------- */
  "S13_INITIAL_RECOVERY-DOC_112F": [
"\n>> [SPECIMEN S13 RECOVERY FILE - CLASSIFIED]",
"\n",
"- Retrieval Unit: 113th Cryo-Lancers, Frostbound Strikers",
"- Oversight: Commander Erza Kael",
"- Date: ██/██/████",
"- Coordinates: ██.███°N, ██.███°W - Site VEIL-B13",
"\n",
">> Overview:",
"- During Operation STAGLIGHT, hostile forces vacated the anomalous VEIL-B13 facility. Unit was dispatched for breach and salvage, under assumption of null-life activity.",
"- Ghostpaw located an entity of uncertain bio-origin designated 'Specimen S13' in Cryo-Containment Unit B, fused to biotech growths and connected to active conduits.",
"- Specimen S13 exhibited no vital signs in traditional biometrics. However, surrounding matter resonated with low-frequency emissions and appeared to decay under observation.",
"- On extraction attempt, containment field ruptured, exposing Ghostpaw to an airborne mutagenic agent. Entity disappeared from sight during evacuation.",
">> CAPTURE OF ENTITY:",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#%%#%#%###%#####%##%#%#%###%%###%%#%%%%%%%%%%",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%####**%#####%#* -##%%###*=+*#*#*####*###%%%%%%%%",
"   %%%%%%%%%%%%%%%%%%#%%%%#####**####*+   *####***  ***#%#%#+ ##*#*###++=##**#%%%%%",
"   %%%%%%%%%%%%#%######%%##*     =*+*+*+ +**#**###* ####%%####%#*#*#+#***+#*##%%%%%",
"   %%%%%%%%%%%%%####-#****-   +++*+=-+**+++++ **#*%**%#%##%%#%########*###*###%%%%%",
"   %%%%%%%%%*##*###+  .*#***#+*++  =+=++++++***   +#*##%#%%##%%%*######*########%%%",
"   %%%%%%%%*+##*%*#+=.#*#*+#*+*   :+-:++**::- :--+= #*#%*#####%####=*#%*##*###%%%%%",
"   %%%%%%##*%:::#%%##*#+#*%#+ ........ :...::..    +  **#%*#**%%%%####%*#*#%%%%%%%%",
"   %%%%%###%:=**#*%#%%%#%### ..    ...:::....        =+++**%***%+*###*##%%%#%%%%%%%",
"   %%%%=###****%#####%##%#* +..    ..      ...     .-+-*+*****########%%%%%%@%%%%%%",
"   %%%%++##%*##*#*%*###%#*  :..    .        ..    :::+::++***%####%#%%#%%#%%%%%%%%%",
"   %%%%**##**+***#=*#*###* -..... .:.       ... .:::+::.++*####%%*%%%%%%%%%%%%%%%%%",
"   %%*%#%%#%%%**==+%%%%++*.::-.-:::-:     .::-. .::++-::+**####%%%%%%%%%%%%%%%%%%%%",
"   %%%%%%#####****=++%++++-.::+-----=:...:::==::::=-=--:+.###%###%%%%%%%%%%%%%%%%%%",
"   %%%%%%%%%%*****#*+**=+*+:.:.==:=+==::::-:+---=+==+-=+..**%##%%%#%%%%%%%%%%%%%%%%",
"   %%%%%%%%%%%*###*%*+##*#++.-.=::==*.+:-: -==--+++*--+=#*###%#%%%%%%%%%%%%%%%%%%%%",
"   %%%%%%%%%%%###***#*+#%*+:=:*..+-++*--:--=+==+***+=+=++##*#%#%%%%%%%#%%%%%%%%%%%%",
"   %%%%%%@%%%%%#*       *+*- *-+.::*+**#=--=++*+  +++=+=*#**#%##%%%%%@%%%%%%%%%%%%%",
"   %%%%%##%####.       .  -+  =+ =.*:-----#+-=++   ++++ #*#+#%%#%%%#%%%%%%%%%%%%%%%",
"   %%%%%%%*#**       .    ==     -= *----++=-+*     +**+ ****#*#%%%##%%%%%%%%%%%%%%",
"   %%%%%%%#*+  .           -    += =+.--+ + =*        ++++****######%%%#%%%%%%%%%%%",
"   %%%%%##**:  :      =*   -:       : ++    *           .*==+*+****##%%%%%%%%%%%%%%",
"   %%%%%%*+=  :.            -            :                  -:-====+######%%%%%%%%%",
"   %%%%%#*=  . .            :                            :+...       +*###%%%%%%%%%",
"   %%%%##*=    :       *    =+     .        * .          .**.            **##%#%%%%",
"   %%%%#**=.   .      #:    :# =          :=++  .       -+*:::               #*#%%%",
"   %%%%*+*=-         #*      #+      .   .-.:.        .:...###--  *            *##%",
"   %%%##+*-.        #*       #**   ++    ++  .+        =:   ##*-: **- :=*+==      #",
"   %%%%#*++        ##        #+*.  *    -##+  *+.    : +=    #* .-***#%%%%%%+=-:   ",
"   %%%%#**+ -    .#=         *     +   -#+%#  -*..=  -+=*+       =+####%%%%%%##+   ",
"   %%%%%#*+     :#     #     #=       .#%*%#  *.:.=  -.=**=      +###*%%%%%%%%%%###",
"   %%%%##++    ##    .##    :#-      .#%%%##  *...= ----* **+   .**####%#%%%%%%%%%%",
"   %%%###*+   ##    ##+     ##      .##%%#*:  +:.-+ ==+:-*.+*+  -**##%#%%%%%%%%%%%%",
"   %%%###**  #*    ##       ##      *%%%#*-.  *:-==+=.:..* ++#=  +*##%%%#%%%%%%%%%%",
"   %%%%##*+ *#    #*       #%#     #%%%%##--   =--=-:.  . # #**-  **#%%#%%%%%%%%%%%",
"   %%%%%##**#    #+      :+-.+    *%%%%%%%=-   -:-=:.    *##+*++:  -#:%#*%#%%%%%%%%",
"   %%%###*.*   .#+   .:-:.   .    *#%%%%%#:- * :-*-.     %%% ++++-  *-%##%%%#%%%%%%",
"   %%%%*#*.#  .+#...:-=.     *    *#%%%%%#=- + :*:::-   #%%% +-=++=  *+#%%%#%%%%%%%",
"   %%%###*.* ..#*:--=:.         :  #%%%%%%#- = **::.*  *%%%%-.=****=  **+*%#%%%%%%%",
"   %%%%%#-.: ..#*--=-.     =   .   *#%%%%%#  + *#:. *  #%%%%*+=****-   **%#%%%%%%%%",
"   %%#%###+:*..##--:.          -   :#%%%%%#* * =.:++*  #%%%%# *=+**+=   +#%%%%%%%%%",
"   %%%#%##-##..:##-..         -:    *#%%%%*. -  =+*+#= *  ##. --++++=+  **#%%%%%%%%",
"   %%%%#%#-%%%...###..        -     :#%%%*   = =+**+*+    ##- -+=+-++--  +#%%%%%%%%",
"   %%%#*%%#%##*+ ..####*     ..      ####    : ++++-+*    +*= =++***=++   -#%%%%%%%",
"   %%%%@%%##*#****=..#..     .     -*###     + ++**.:+     *=.-+***++==-   #%%%%%%%",
"   %%%%%%%%#######**:#+=+++   =-=*##%%%#    -= ++***=+     +++ ++*+++.==   ##%%%%%%",
"   %#%%%%%%#%##*##+++==*+=+  ==###%%%%%##   -- -*****+    =++: ++=*++--:-   *%%%%%%",
"   %%%%%#%##%%#.       =-:   +==#####%#*:   +-  ** ++=  +++++= =+=++++-:.   +#%%%%%",
"   %%%#%%%%#+:.                           . ==  +*:+*++ +***+=.--+--:--.-    *#%%%%",
"   %%%#%%%%#::#.                       :::- =- :**++++= +#***: :=+=-=:....    *#%%%",
"   %%%%%%%%%-.+#**                ==*+=+=-  -:  *+++**+ **#**: :.-+--:....    =+#%%",
"   %%%%%#@%%%%###**#*        +=++*+***+++: :-:  +*+++++ +###+=: :-::-.-..      *#%%",
"   %%%%%%%%%%%%%%%%##*##** +###*#*.##=*+:+ :-:  +*++++: .*#***=   -.-...:      +#%%",
"   %%%%%%%%%%%%%%%%%+##%## ######%%%+%+#== ::.  ++=+++=  *####*-   ......       #%%",
"   %%%%%@%%%%%%%%%%%+-%%%*=*%#%#%%%##%**-  ::: -**=-+.:  *###**==   :... .  .   *#%",
"   %%%%%%%%%%%%%%%%%%%%%%%# %%#%%%%%%%#++ .::. -*+.=-:.  *##+##*+=   . . ...    -*#",
"   %%%%%%%%%%%%%%%%%%%%%%%% #%%%%%%%#%=+- .... .** :-..  #%%%##**++        ..    *#",
"   %%%%%%%%%%%%%%%%%%%%%%%% %%%#%#%%%#*+  . .  :** ...:. *#%%#%###*+    .....    :#",
"   %%%%%%%%%%%%%%%%%%%%%%%%#%%%#%#%%%#*+       **** .... *#%%#####*++      .      *",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%##*    -   *##+ ...: :##%%%%###+*+=     ..    =",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%**   =+   ###+   .. .#%%%%%%###**+=       .   ",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#-   +*   *###+  ... ##%%%%%*#%*#*++          ",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#+   =**   *#%%*+     #*%##%%%%###**+++        ",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#+   *#*   *##%#*      ###%%%%%%%###*++=       ",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%*+   *#*   +##%%*+     *##%%#%%%%%###*++=      ",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#*    ###   *#%%##+     +*%%%%%%%%%%###**+=     ",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%**   *##*   *#%%%%*=    +#%%%%%%%%%%%###*#+=    ",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#=   *###+  *#%%%%%#     *#%%%%%%%%%%%%###*+=   ",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#*    ##%#+  *%%%%%*#*    *#%%%%%%%%%%%%##***+   ",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#*   ##%%#+  *%%%%%%%#    +#%%%%%%%%%%%%%####*+  ",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#+   *%%##*  +%%%=%%+##   :##%%%%%%%%%%%%%%#***- ",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%*+    #%%#%+  *%%%%%%%%#    *#%%%%%%%%%%%%%%#*#*+ ",
"   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#*   *#%%%#+  #%%%%%%%%%*   *#%%%%%%%%%%%%%%%###+-",
"(Recovered via Drone Uplink V13-B - Captured from Ghostpaw's DAT-BINDER-9)",
"\n",
">> Experimental Findings:",
"• Ghostpaw's exposure triggered latent neurological aberrations 3 days post-incident: tremors, heightened visual field, inability to retain sleep. Standard detox failed.",
"• Entity's residue measured incompatible with current matter theory. Lustra-exposed samples rendered inert.",
"• Cryo-Vault personnel have since reported auditory phenomena at VEIL-B13. Disciplinary records pending.",
"\n",
">> Status:",
"- Ghostpaw marked as VOID-TOUCHED. Voluntarily re-enlisted under Section ██.",
"- Entity remains unrecovered. Future sightings will use Signal Tag: [S13-VEILSHADOW]",
"- END REPORT",
    ],
  "S13-B13-LOG_0421A": [    
"\n>> [LOG TYPE: AUDIO // Transcription Active]",
"- ...This is Ghostpaw. Mission timestamp... doesn’t matter. I made it back. I think. I’m—",
"\n> [long silence]",
"\n- I don't think anyone will believe me.",
"\n> [static interference – 3.5s]",
"\n- They said S13 couldn’t move. Said it was frozen. Locked in crypto-stasis since the Cryo-War's final hours. I believed them.",
"- I saw it. I saw it. Not just the body. The face. It looked at me. Not like a predator—no. It looked like... like Erza did when I got shot that one time. That breath-held kind of panic. That quiet sorrow you get when you know someone’s breaking right in front of you, and you can’t stop it.",
"- I don’t know how to describe it. I don’t even know if I was awake anymore. I blinked, and it was like—I was in time’s grave.",
"\n> [muffled breath – pacing can be heard]",
"\n- Ten seconds. Ten FUCKING seconds on the mission timer. That’s all the others will ever see.",
"- But I lived entire eternities in those ten seconds. I died a thousand deaths in a place where even death doesn’t mean anything. Time had no hands there. No order. No mercy. I stood in the eye of a star and heard the screams of civilizations burned to dust and then rebuilt from that same dust, only to be erased again. I saw oceans turn to glass. I felt the walls of reality drip around me like candlewax.",
"- And through it all... she looked at me. She. That thing—that god—looked at me with more humanity than anything I’ve seen since the war. It didn’t just see me... it knew me. Every wound. Every breath I took to hide my fear. Every scream I buried in the snow.",
"- It pitied me. Loved me.",
"- She saw herself in me. And she wept.",
"\n> [tape hiss increases – an audio fragment plays faintly in the background: Side B, Track 4 – “How to Disappear Completely” by Radiohead]",
"\n- I thought she would kill me. No. Worse. I thought she'd make me understand her.",
"- I was weightless. I was known. And in that knowing... I was erased.",
"- You ever hear the phrase, “No one shall see My face and live?”",
"- ...I did.",
"- I saw the face of something born in silence. A mother who never got to cradle her children. A god buried alive beneath our fear. And for one second... I think she was sorry.",
"\n> [audio distortion spike – unclear sounds, like distant whispers or reversed speech]",
"\n- And I wanted to understand her too. And oh gods help me, I did.",
"\n> [Ghostpaw laughs. Dry. Unstable.]",
"\n- But she let me go. Like she knew I couldn’t carry it. Like... like a mother letting her child forget the worst of what he saw.",
"\n> [soft inhale]",
"\n- I’m back now. My body’s here. But...",
"- I don’t know how to be this anymore.",
"\n> [hiss fades under the continued song]",
"\n- ...Erza’s tape was still playing in my pack. I think it kept me sane. 'How to Disappear Completely.' That was the track. Funny, huh?",
"- ...I don’t think I’m all here.",
"\n> [AUDIO RECORDING ENDS]",
"\nThe following is a sketch of the entity S13's face, drawn by Ghostpaw:",
"\n@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%%%#######@@@%%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%%#*:-::::-----::*+%#%@%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@%-@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%##::...............::::++%#%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%%%%%%%%%#+:::..::-=-:-...........:::-:%#%%@@@@@@@@@@@@@@@@@@@@@@@@@@@%-@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@--@@@@@@@@@@@@@@%%#%+:====---*::..----...........:::......::::*#%%%%%%%%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%%%==-:.....::::::..--.:............::::.:.....:.::::::=++=+*@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%%=:-:-....::::::::.:+::-+:...:....:......:::::-..:::::..::-+=+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%%-=+=:...-:.:....:::.-::....:..=+.....:...:::::-::..:.:==+###%%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%%=+:.....-........:..-=-:......--=:..............:::::::::..:::##%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%%--:.....-.:...:.........:.:=..=............:==:::.:.::-=:.....:::::##%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%@#-:.....-:::.:-.........::.....:.............:::...:-:::::::+-::::.-::-:#%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%%#-:......-:...:...+-:.......:.-:......:...:....=:..:-...:-::::::::-::::-*=+%%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@%%%%%%%#+*:......:-:......=:...........:-...=-..:.:::.=....:..:--...::::::::::::::+:=%@%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@%++++-==-.......:-.......:.........:.:-::*....-:...::::.=:.....:..::...-:::::.-..:::*+%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@%#%%*++*:.....=:...........:......-:.::-:-....=:.....:::.=......:.:.....=.::::::.:-:-#%@@@@@@@@@@@@@@@@@@:@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@%%#-....:-.......:....:.....::..:-:...-....-*....:.::......:..:-.....:+::::.=...*#%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@%%*:....:-.......:...-:...:..:...-::.......::=......::::*.......:*......-.::....::+@%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@%*:....::.......:........::.................:*-:....:=.:::........-.......:::.....::%%%@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@%+::...:::......:...:....:........+:..........:%.......::::..................::::...::##%@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@%@*-.:.-.:..:..:....::...::........+...........::-:......-:.:......:.............:::...-##%@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@%=#.:::::....::....::....:.....:::*=:.......-.....*.+.....:-.:.......:.......:......:....@#%@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@%+#...:=...::.....:.:..:......:::+*#-......-:....:-:.=.....=-:=.......:.:.....+=..........-%%@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@%%==:::...:-......:.:....-...::::.*#*=......::.....:...=......=::.......:.-....+.=--.:.....:+%%@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@%%-:..:.:::::.:.........:=...:::::####-=....-::.....:....+......-:........::....:*::.::......:*%%@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@%#=.:.-........:....:.:.:.:...::::######-.....:::.........:+%::+=:*::.......::.....%::.:-:..:..-*%%@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@%:-.*..:.......:......=.::*...:-**#-+*##*::....=::-....:-..:==++-#:=***:......=....:*:...+.:...-:-@%@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@+%@@@@@@@@%#=-+:::..............:-.:.=.:=:::*.-==*-..+....--::......:--.=.--.:#:-.+*=.....=.....::.......::-=-%@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@%+=-#:.-...:....-.....=:.:.-...:=-::-:--=::#::...:..-:....:-...:-----::==+......-.....+....:.....@-+%@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@%%+=--:-...-.:...::...:::-:.:::=====+.:++=%#*#-....::::.:.....:---=-=+=-:+*-:....:....::.:........=#%@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@%%+*-+:+.==:::...=-:..-:::..-::--#######%####*---....-...+:....:.::-*#####-:..-.....:.-...........=*%%@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@%@%%..:.+-.::..:::-..-:::=:-:--*#############*=--.....=::+=:...::+*#+-##*--.......=-.--.::.:..:..#.=-%%@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@%%+:..:=-:.-....:.==-:.::.=#+*##*#:*##*#%####***-:--#**+:::----.*==*-:**=:.:..:.==+-.*.:.....:....=++*@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@%@%%#=..:-:*..:.:::..=:=:.::::+*#-:::::::+.::-###****+*##**=+-#:::--:-=.:-:+-:...:..-=:..=.....:-..:.%%%@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@%@@%%%-=....:::::-.:::::+..-..::::+*##:::-===::-+#############+###*+::=---:=-##+:.....*+:..........+..:-%%@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@%%+++....*:::*..::..:.=:-...:.-*-###*%####%#############################%#*#=:.....*.:...:......#.:-%%@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@%@++-:.....:...:-:::..:::.::..::+--*########################################*=:......+:....:......=#--%%@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@%#%%##.....:...:.:::::::==....:-+++###%%%###########################%#%###**##-....:.:....:....::%=+%%@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@%%@#:.::......:...:.:.:.+:=+.:+*%##=-:**+-#*##################=*--*++%+++#+:-.:.-.......::.+-:#%%%@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@%@%%:::+-:..-...:....::.:+:=.+=.-*::::-::-=:-=################*:::-=:-==--#%+..:.-.......-+.:.%%%@@@@@@@@@@@@%.%@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@%#=-+#-...-:::::.::...*-.#*+*:+#%-:-=--=++################%#++=--====#*#-+:::.-......:..-=%%%@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@%%#++%%%+:**.:-....::.+=-=-##+#*######%#################################+-:+:+=.....::.:+:%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@%%%@%%@-:++-::.+.:::.:=+:#############################################**:.........=::+%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@%%%**--::---:.-:.-:**##########################################*++:.........-.-*%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%%#:+.:::.::-..::##############################=**##%########*::....::.:=-*+:%%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%%+::..:-.:.*:.:..###########################%*:*--#=-*#####+::...::::::-%%#%%%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%%=-:-..::+:*::.:.:*##########################-:---==:=-##*=::..:.:.=::*%%%@%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%%-:+-....:.+--::-.:==#########################*:-=---=####-.::.:-:-:+=%%%%%%%%@@@%*@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%%+##*::.:...::.::=-:*+##################################*::...:--=-=%%%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%#+%%#.::.-.:...:...--*###############################+:+.::::@*-==%%%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%%#:-:+=..:.:...:::*%##########################*++-==.::.-@%@%%@%%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%%%=%%*::.:..:.:.+=%########################**=:::-.:+-+-%%%@%%%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%%%%::.:::.:::+:--+*###################+*-:::::.:-**=%%%%%%%%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%%%+=::::#=:::+:-::::#################*-::::::=.-#%@*#%%%%%%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%%#++=%@--##-::*:::::::-:*+=+=+******:-::::::::#:=-##%#%%%%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%%%%%%#=%%#:=@##%-#:::::.::::::::::::::::::::.:::-#*-+-#%%%%%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%%%%%%%%%%%++=%%###:-:.:...::::::::::::::.:::::::.%@%%+*#%%%%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%@@%%%%%%%%%%#-%%%%%%::-:::::..:..::::::::::::::::::*=%%%%%%%%%%@@@@@@@@@@@@@@@@@@@@@%@@@%@@@@@@@@@%@%%@",
"@@@@@@@@@@@@@@@@@%@%%%%%%%%@@@%%%%%%%%%%%%%%%%%%%++%%%-*-:::::.:....:::::::::.::.:::::-**@%%%%%%%%%%%%@@@@@@@@@@@@%%%%%%%%%%%%%%%%%%%%%%%%%",
"@@@@@@@@@@@@@@@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#-*-:::.:::.....:::::::::..::::::::++#%%%%%%%%%%%%%%%%@@@@@%%%%%%%%%%%%%%%%%%%%%%%%%%%",
"@@@@@@@@@@@@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%##+:--:::.:::::...::::::....::::::::+-%%%%%%%%%%#-%%%%%%%@@%%%%%%%%%%%%%%%%%%%%%%%%%%%%",
"%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%##=-=---::::...::::.::::...:::::...::::::##%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%",
    ],
};