export const dossierNodes = {
    "DIREWOLF_RESCUE-DOC_78A": { id: "DIREWOLF_RESCUE-DOC_78A", label: "DIREWOLF EXTRACTION REPORT", folder:"Dossier Compilation" },
    "LUSTRA_CHEM-USE_LOG_77B-A": { id: "LUSTRA_CHEM-USE_LOG_77B-A", label: "INCIDENT REPORT: NIGHT FURY AMBUSH", folder: "Cryo-Chamber Grid" }
  };
  
  export const dossierResponses = {
    "DIREWOLF_RESCUE-DOC_78A": [
"\n> [DIREWOLF EXTRACTION REPORT]",
"Unit: 113th Cryo-Lancers, Frostbound Strikers",
"Subject: Ghostpaw - Field Medic / Operative",
"Date: ██/██/████",
"Location: Peripheral Zone, Cryo-Station Theta-V Approach",
"\n",
">> Overview:",
"During a routine patrol near the compound's southern ingress, Ghostpaw encountered an unexpected enemy ambush resulting in the dispersal of squad elements. Amid the confusion and disarray, operative Ghostpaw located a critically injured direwolf pup—severely mauled by hostile forces designated as “The Hollowed.” This extraction was recorded as a non-combat casualty operation with significant tactical and morale implications.",
"\n",
">> Field Observations:",
"• The pup was isolated in a narrow ice alcove, its fur matted and blood-soaked, exhibiting signs of severe lacerations.",
"• Enemy forces, utilizing low-angle suppressive fire and chemical agents, had abandoned the creature after overwhelming local defenses. Its survival was unexpected.",
"• Ghostpaw immediately provided emergency field care; stabilizing the pup with improvised trauma techniques learned during his medic training.",
"• Commander Erza, upon arrival, documented his initial disapproval—her usual stern tone softened upon witnessing his persistence and the pup's vulnerability.",
"• Subsequent drone footage later confirmed the pup's extraction under heavy enemy engagement. Erza authorized additional resources for the pup's care, recognizing the symbolic value of its rescue.",
"\n",
">> Operational Impact:",
"- The direwolf rescue not only showcased Ghostpaw's compassion and medical expertise under fire but also became a turning point in unit morale. The incident further reinforced his codename, 'Ghostpaw,' reflecting his silent determination and the eerie resemblance of his gloved hands to a dire wolf's paw.",
"- Intelligence indicated that the rescued pup might serve both as a tactical scout in small-unit operations and as an emblem of resilience for the squad.",
"- The event is now integrated into squad lore and remains a key motivator in subsequent operations. A follow-up dossier has been created for “The Dire Wolf Companion” to track its progress and any influence on field tactics.",
"\n",
">> Conclusion:",
"The extraction operation was a success against overwhelming odds. It highlighted both the vulnerabilities inherent in frontline combat and the unexpected bonds that form amidst chaos.",
"End of Report."],
    "LUSTRA_CHEM-USE_LOG_77B-A": [
"\n> [INCIDENT REPORT: NIGHT FURY AMBUSH]",
"Unit: 113th Cryo-Lancers, Frostbound Strikers",
"Subject: Ghostpaw - Field Medic / Squad Report Writer",
"Date: ██/██/████",
"Location: Northern Expanse, Near Frostline Ridge",
"\n",
">> Incident Summary:",
"During an operation designated “Night Fury,” Ghostpaw was deployed as part of a recon and extraction mission in the hostile northern expanse. An ambush by enemy forces—using both conventional ordnance and chemical distracters—shattered the initial formation. Ghostpaw's rapid field response not only saved multiple lives but also secured critical intel that later contributed to a strategic counter-offensive.",
"\n",
">> Event Chronology:",
"• As dusk descended, unit positions were illuminated by controlled bursts of Lustra, ensuring operational visibility. However, an enemy volley caught the squad off-guard. The ambush produced disorienting bursts of chemical fire, temporarily obscuring vision and hampering communication.",
"• Amidst the chaos, Ghostpaw, stationed at the forward medical post, was forced into an improvised leadership role when primary medics and radio operators were incapacitated.",
"• Displaying remarkable calm and adaptability, he initiated emergency triage while simultaneously establishing a secure forward perimeter. His silent efficiency under duress enabled him to document events in real-time using his portable Data Recorder ('DAT-BINDER-9'), as is his duty.",
"• Fragmented memories captured in his log indicate a moment of stark realization: as the enemy advanced, he witnessed an almost uncanny synchronization—enemy movements paused, and their chaos momentarily stilled—triggering an internal, almost preternatural clarity.",
"• Ghostpaw's subsequent decision to split small groups and evacuate critical wounded personnel, while simultaneously relaying enemy positions via encoded field messages, prevented further casualties. His actions were later credited as the decisive factor in maintaining unit cohesion during the assault.",
"\n",
">> Critical Observations:",
"- The ambush incident, later dubbed “Night Fury,” established Ghostpaw's reputation as not only a compassionate medic but also a tactical improvisor. His role as the squad report writer proved invaluable; his detailed logs provided high-command with clear situational analysis post-engagement.",
"- Command noted that Ghostpaw's non-verbal communication—the way his gloved, “paws-like” hands moved methodically over injured personnel—conveyed an unwavering resolve that influenced surviving members to perform beyond standard expectations.",
"- Analysis of environmental data correlated with the use of Lustra confirms that the temporary light bursts, although designed for distraction, inadvertently synchronized enemy positions, giving Ghostpaw a critical window to act.",
"\n",
">> After-Action and Recommendations:",
"- Comprehensive debriefings with surviving squad members recommended that Ghostpaw's techniques and decision-making be further studied and integrated into training modules for future emergency medics.",
"- Additional research on the psychological phenomenon observed during the ambush (“the stillness of Night Fury”) is underway to determine if it represents a temporary state of heightened situational awareness—a potential byproduct of exposure to combat stress and battlefield lighting effects.",
"\n",
">> Conclusion:",
"The incident demonstrates that, even under extreme adversity, Ghostpaw's innate discipline and silent vigilance can pivot a collapsing operation into a controlled extraction. His documentation and actions during “Night Fury” remain a guiding example of valor and ingenuity.",
"End of Report."
    ]
  };